use rusqlite::{params, Connection};
use serde_json::{json, Map, Value};
use std::collections::{BTreeSet, HashMap};
use std::env;
use std::error::Error;
use std::fs;
use std::io;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{self, Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};
use uuid::Uuid;

type HostResult<T> = Result<T, Box<dyn Error>>;

fn main() {
    if let Err(err) = run(env::args().collect()) {
        eprintln!("error: {err}");
        std::process::exit(1);
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    match args.get(1).map(String::as_str) {
        Some("pve-conf-to-nix") => pve_conf_to_nix_main(&args[2..]),
        Some("reconcile") => reconcile_main(&args[2..]),
        Some("state") => state_main(&args[2..]),
        Some("-h") | Some("--help") | None => {
            print_usage();
            Ok(())
        }
        Some("-V") | Some("--version") => {
            println!("proxnix-host {}", version());
            Ok(())
        }
        Some(command) => Err(format!("unknown subcommand: {command}")),
    }
}

fn version() -> &'static str {
    option_env!("PROXNIX_VERSION").unwrap_or(env!("CARGO_PKG_VERSION"))
}

fn print_usage() {
    println!(
        "\
Usage:
  proxnix-host pve-conf-to-nix --pve-conf <path> --out-dir <dir>
  proxnix-host reconcile podman-secrets --rootfs <path> --vmid <vmid> --secrets-dir <dir>
  proxnix-host state [--db <path>] <init|observe-container|observe-closure|record-attempt>
  proxnix-host --version
"
    );
}

fn reconcile_main(args: &[String]) -> Result<(), String> {
    match args.first().map(String::as_str) {
        Some("podman-secrets") => reconcile_podman_secrets_main(&args[1..]),
        Some("-h") | Some("--help") | None => {
            print_usage();
            Ok(())
        }
        Some(command) => Err(format!("unknown reconcile subcommand: {command}")),
    }
}

fn pve_conf_to_nix_main(args: &[String]) -> Result<(), String> {
    let mut pve_conf: Option<PathBuf> = None;
    let mut out_dir: Option<PathBuf> = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--pve-conf" => {
                index += 1;
                pve_conf = args.get(index).map(PathBuf::from);
            }
            "--out-dir" => {
                index += 1;
                out_dir = args.get(index).map(PathBuf::from);
            }
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            other => return Err(format!("unknown pve-conf-to-nix argument: {other}")),
        }
        index += 1;
    }

    let pve_conf = pve_conf.ok_or("--pve-conf is required")?;
    let out_dir = out_dir.ok_or("--out-dir is required")?;
    let rendered = generate_proxmox_nix(
        &parse_pve_conf(&pve_conf)
            .map_err(|err| format!("failed to read {}: {err}", pve_conf.display()))?,
    );

    fs::create_dir_all(&out_dir)
        .map_err(|err| format!("failed to create {}: {err}", out_dir.display()))?;
    write_if_changed(&out_dir.join("proxmox.nix"), &rendered).map_err(|err| {
        format!(
            "failed to write {}: {err}",
            out_dir.join("proxmox.nix").display()
        )
    })?;
    Ok(())
}

#[derive(Debug, Default, PartialEq, Eq)]
struct ProxmoxNixData {
    hostname: Option<String>,
    nameservers: Vec<String>,
    search_domain: Option<String>,
    ssh_keys: Vec<String>,
}

fn parse_pve_conf(path: &Path) -> io::Result<ProxmoxNixData> {
    let content = fs::read_to_string(path)?;
    Ok(parse_pve_conf_content(&content))
}

fn parse_pve_conf_content(content: &str) -> ProxmoxNixData {
    let mut raw = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
            continue;
        }
        let Some((key, value)) = line.split_once(": ") else {
            continue;
        };
        raw.insert(key.trim().to_owned(), value.trim().to_owned());
    }

    ProxmoxNixData {
        hostname: raw
            .get("hostname")
            .filter(|value| !value.is_empty())
            .cloned(),
        nameservers: raw
            .get("nameserver")
            .map(|value| value.split_whitespace().map(str::to_owned).collect())
            .unwrap_or_default(),
        search_domain: raw
            .get("searchdomain")
            .filter(|value| !value.is_empty())
            .cloned(),
        ssh_keys: decode_ssh_public_keys(raw.get("ssh-public-keys").map(String::as_str)),
    }
}

fn generate_proxmox_nix(data: &ProxmoxNixData) -> String {
    let mut lines = vec![
        format!(
            "# Generated by pve-conf-to-nix.py {} do not edit by hand.",
            '\u{2014}'
        ),
        "{ lib, ... }: {".to_owned(),
    ];

    if let Some(hostname) = &data.hostname {
        lines.push(format!(
            "  networking.hostName = lib.mkForce {};",
            nix_str(hostname)
        ));
    }
    if !data.nameservers.is_empty() {
        lines.push(format!(
            "  networking.nameservers = lib.mkForce {};",
            nix_str_list(&data.nameservers)
        ));
    }
    if let Some(search_domain) = &data.search_domain {
        lines.push(format!(
            "  networking.search = lib.mkForce [ {} ];",
            nix_str(search_domain)
        ));
    }
    if !data.ssh_keys.is_empty() {
        lines.push(format!(
            "  users.users.root.openssh.authorizedKeys.keys = lib.mkForce {};",
            nix_str_list(&data.ssh_keys)
        ));
    }

    lines.push("}".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if path.exists() && fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }
    fs::write(path, content)
}

fn decode_ssh_public_keys(raw_value: Option<&str>) -> Vec<String> {
    let Some(raw_value) = raw_value else {
        return Vec::new();
    };
    let decoded = percent_decode_lossy(raw_value).replace("\\n", "\n");
    decoded
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.trim_start().starts_with('#'))
        .map(str::to_owned)
        .collect()
}

fn percent_decode_lossy(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;

    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            if let (Some(high), Some(low)) =
                (hex_value(bytes[index + 1]), hex_value(bytes[index + 2]))
            {
                decoded.push((high << 4) | low);
                index += 3;
                continue;
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }

    String::from_utf8_lossy(&decoded).into_owned()
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

fn nix_str(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${");
    format!("\"{escaped}\"")
}

fn nix_str_list(items: &[String]) -> String {
    let rendered = items
        .iter()
        .map(|item| nix_str(item))
        .collect::<Vec<_>>()
        .join(" ");
    format!("[ {rendered} ]")
}

const DEFAULT_STATE_DB: &str = "/var/lib/proxnix/state/proxnix-reconciler.sqlite";

const STATE_SCHEMA: &str = r#"
create table if not exists container_observations (
  vmid integer primary key,
  node text not null,
  desired_system text,
  current_system text,
  container_is_local integer not null,
  last_phase text,
  last_status text,
  last_error text,
  updated_at text not null
);

create table if not exists closure_observations (
  store_path text primary key,
  host_has_closure integer,
  container_has_closure integer,
  protected_by_host_gc_root integer not null default 0,
  gc_root_path text,
  updated_at text not null
);

create table if not exists deployment_attempts (
  id integer primary key autoincrement,
  vmid integer not null,
  store_path text,
  phase text not null,
  status text not null,
  error text,
  started_at text not null,
  finished_at text
);

create index if not exists deployment_attempts_vmid_idx
  on deployment_attempts(vmid);
"#;

fn state_main(args: &[String]) -> Result<(), String> {
    state_main_inner(args).map_err(|err| format!("state command failed: {err}"))
}

fn state_main_inner(args: &[String]) -> HostResult<()> {
    let mut db_path = PathBuf::from(DEFAULT_STATE_DB);
    let mut index = 0;

    while index < args.len() {
        match args[index].as_str() {
            "--db" => {
                index += 1;
                db_path = PathBuf::from(
                    args.get(index)
                        .ok_or_else(|| invalid_input("--db requires a value"))?,
                );
                index += 1;
            }
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            _ => break,
        }
    }

    let command = args
        .get(index)
        .ok_or_else(|| invalid_input("state subcommand is required"))?;
    let command_args = &args[index + 1..];
    let conn = connect_state_db(&db_path)?;

    match command.as_str() {
        "init" => init_state_db(&conn)?,
        "observe-container" => {
            let observation = parse_container_observation(command_args).map_err(invalid_input)?;
            observe_container(&conn, &observation)?;
        }
        "observe-closure" => {
            let observation = parse_closure_observation(command_args).map_err(invalid_input)?;
            observe_closure(&conn, &observation)?;
        }
        "record-attempt" => {
            let attempt = parse_deployment_attempt(command_args).map_err(invalid_input)?;
            let attempt_id = record_deployment_attempt(&conn, &attempt)?;
            println!("{attempt_id}");
        }
        other => return Err(invalid_input(format!("unknown state subcommand: {other}")).into()),
    }

    Ok(())
}

fn invalid_input(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

#[derive(Debug, PartialEq, Eq)]
struct ContainerObservation {
    vmid: i64,
    node: String,
    desired_system: Option<String>,
    current_system: Option<String>,
    container_is_local: bool,
    last_phase: Option<String>,
    last_status: Option<String>,
    last_error: Option<String>,
}

#[derive(Debug, PartialEq, Eq)]
struct ClosureObservation {
    store_path: String,
    host_has_closure: Option<bool>,
    container_has_closure: Option<bool>,
    protected_by_host_gc_root: Option<bool>,
    gc_root_path: Option<String>,
}

#[derive(Debug, PartialEq, Eq)]
struct DeploymentAttempt {
    vmid: i64,
    store_path: Option<String>,
    phase: String,
    status: String,
    error: Option<String>,
    finished_at: Option<String>,
}

fn parse_container_observation(args: &[String]) -> Result<ContainerObservation, String> {
    let mut vmid = None;
    let mut node = None;
    let mut desired_system = None;
    let mut current_system = None;
    let mut container_is_local = None;
    let mut last_phase = None;
    let mut last_status = None;
    let mut last_error = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--vmid" => vmid = Some(parse_i64_arg(args, &mut index, "--vmid")?),
            "--node" => node = Some(take_arg(args, &mut index, "--node")?),
            "--desired-system" => {
                desired_system = Some(take_arg(args, &mut index, "--desired-system")?)
            }
            "--current-system" => {
                current_system = Some(take_arg(args, &mut index, "--current-system")?)
            }
            "--container-is-local" => {
                container_is_local = Some(parse_bool_arg(args, &mut index, "--container-is-local")?)
            }
            "--last-phase" => last_phase = Some(take_arg(args, &mut index, "--last-phase")?),
            "--last-status" => last_status = Some(take_arg(args, &mut index, "--last-status")?),
            "--last-error" => last_error = Some(take_arg(args, &mut index, "--last-error")?),
            other => return Err(format!("unknown observe-container argument: {other}")),
        }
        index += 1;
    }

    Ok(ContainerObservation {
        vmid: vmid.ok_or("--vmid is required")?,
        node: node.ok_or("--node is required")?,
        desired_system,
        current_system,
        container_is_local: container_is_local.ok_or("--container-is-local is required")?,
        last_phase,
        last_status,
        last_error,
    })
}

fn parse_closure_observation(args: &[String]) -> Result<ClosureObservation, String> {
    let mut store_path = None;
    let mut host_has_closure = None;
    let mut container_has_closure = None;
    let mut protected_by_host_gc_root = None;
    let mut gc_root_path = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--store-path" => store_path = Some(take_arg(args, &mut index, "--store-path")?),
            "--host-has-closure" => {
                host_has_closure = Some(parse_bool_arg(args, &mut index, "--host-has-closure")?)
            }
            "--container-has-closure" => {
                container_has_closure =
                    Some(parse_bool_arg(args, &mut index, "--container-has-closure")?)
            }
            "--protected-by-host-gc-root" => {
                protected_by_host_gc_root = Some(parse_bool_arg(
                    args,
                    &mut index,
                    "--protected-by-host-gc-root",
                )?)
            }
            "--gc-root-path" => gc_root_path = Some(take_arg(args, &mut index, "--gc-root-path")?),
            other => return Err(format!("unknown observe-closure argument: {other}")),
        }
        index += 1;
    }

    Ok(ClosureObservation {
        store_path: store_path.ok_or("--store-path is required")?,
        host_has_closure,
        container_has_closure,
        protected_by_host_gc_root,
        gc_root_path,
    })
}

fn parse_deployment_attempt(args: &[String]) -> Result<DeploymentAttempt, String> {
    let mut vmid = None;
    let mut store_path = None;
    let mut phase = None;
    let mut status = None;
    let mut error = None;
    let mut finished_at = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--vmid" => vmid = Some(parse_i64_arg(args, &mut index, "--vmid")?),
            "--store-path" => store_path = Some(take_arg(args, &mut index, "--store-path")?),
            "--phase" => phase = Some(take_arg(args, &mut index, "--phase")?),
            "--status" => status = Some(take_arg(args, &mut index, "--status")?),
            "--error" => error = Some(take_arg(args, &mut index, "--error")?),
            "--finished-at" => finished_at = Some(take_arg(args, &mut index, "--finished-at")?),
            other => return Err(format!("unknown record-attempt argument: {other}")),
        }
        index += 1;
    }

    Ok(DeploymentAttempt {
        vmid: vmid.ok_or("--vmid is required")?,
        store_path,
        phase: phase.ok_or("--phase is required")?,
        status: status.ok_or("--status is required")?,
        error,
        finished_at,
    })
}

fn take_arg(args: &[String], index: &mut usize, flag: &str) -> Result<String, String> {
    *index += 1;
    args.get(*index)
        .cloned()
        .ok_or_else(|| format!("{flag} requires a value"))
}

fn parse_i64_arg(args: &[String], index: &mut usize, flag: &str) -> Result<i64, String> {
    take_arg(args, index, flag)?
        .parse::<i64>()
        .map_err(|err| format!("{flag} must be an integer: {err}"))
}

fn parse_bool_arg(args: &[String], index: &mut usize, flag: &str) -> Result<bool, String> {
    parse_state_bool(&take_arg(args, index, flag)?)
}

fn parse_state_bool(value: &str) -> Result<bool, String> {
    match value.trim().to_ascii_lowercase().as_str() {
        "1" | "true" | "yes" | "y" => Ok(true),
        "0" | "false" | "no" | "n" => Ok(false),
        _ => Err(format!("invalid boolean: {value}")),
    }
}

fn connect_state_db(db_path: &Path) -> HostResult<Connection> {
    if let Some(parent) = db_path.parent() {
        fs::create_dir_all(parent)?;
    }
    Ok(Connection::open(db_path)?)
}

fn init_state_db(conn: &Connection) -> rusqlite::Result<()> {
    conn.execute_batch(STATE_SCHEMA)
}

fn observe_container(
    conn: &Connection,
    observation: &ContainerObservation,
) -> rusqlite::Result<()> {
    init_state_db(conn)?;
    conn.execute(
        r#"
        insert into container_observations (
          vmid, node, desired_system, current_system, container_is_local,
          last_phase, last_status, last_error, updated_at
        )
        values (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
        on conflict(vmid) do update set
          node = excluded.node,
          desired_system = excluded.desired_system,
          current_system = excluded.current_system,
          container_is_local = excluded.container_is_local,
          last_phase = excluded.last_phase,
          last_status = excluded.last_status,
          last_error = excluded.last_error,
          updated_at = excluded.updated_at
        "#,
        params![
            observation.vmid,
            observation.node.as_str(),
            observation.desired_system.as_deref(),
            observation.current_system.as_deref(),
            bool_to_int(Some(observation.container_is_local)),
            observation.last_phase.as_deref(),
            observation.last_status.as_deref(),
            observation.last_error.as_deref(),
            utc_now_seconds_z(),
        ],
    )?;
    Ok(())
}

fn observe_closure(conn: &Connection, observation: &ClosureObservation) -> rusqlite::Result<()> {
    init_state_db(conn)?;
    let protected_by_host_gc_root = observation.protected_by_host_gc_root.unwrap_or_else(|| {
        gcroot_protects_store_path(&observation.store_path, observation.gc_root_path.as_deref())
    });
    conn.execute(
        r#"
        insert into closure_observations (
          store_path, host_has_closure, container_has_closure,
          protected_by_host_gc_root, gc_root_path, updated_at
        )
        values (?1, ?2, ?3, ?4, ?5, ?6)
        on conflict(store_path) do update set
          host_has_closure = excluded.host_has_closure,
          container_has_closure = excluded.container_has_closure,
          protected_by_host_gc_root = excluded.protected_by_host_gc_root,
          gc_root_path = excluded.gc_root_path,
          updated_at = excluded.updated_at
        "#,
        params![
            observation.store_path.as_str(),
            bool_to_int(observation.host_has_closure),
            bool_to_int(observation.container_has_closure),
            bool_to_int(Some(protected_by_host_gc_root)),
            observation.gc_root_path.as_deref(),
            utc_now_seconds_z(),
        ],
    )?;
    Ok(())
}

fn record_deployment_attempt(
    conn: &Connection,
    attempt: &DeploymentAttempt,
) -> rusqlite::Result<i64> {
    init_state_db(conn)?;
    conn.execute(
        r#"
        insert into deployment_attempts (
          vmid, store_path, phase, status, error, started_at, finished_at
        )
        values (?1, ?2, ?3, ?4, ?5, ?6, ?7)
        "#,
        params![
            attempt.vmid,
            attempt.store_path.as_deref(),
            attempt.phase.as_str(),
            attempt.status.as_str(),
            attempt.error.as_deref(),
            utc_now_seconds_z(),
            attempt.finished_at.as_deref(),
        ],
    )?;
    Ok(conn.last_insert_rowid())
}

fn bool_to_int(value: Option<bool>) -> Option<i64> {
    value.map(|value| if value { 1 } else { 0 })
}

fn gcroot_protects_store_path(store_path: &str, gc_root_path: Option<&str>) -> bool {
    let Some(gc_root_path) = gc_root_path else {
        return false;
    };
    let root = Path::new(gc_root_path);
    if !fs::symlink_metadata(root).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
        return false;
    }
    if fs::read_link(root).ok().as_deref() != Some(Path::new(store_path)) {
        return false;
    }
    let Some(nix_store) = find_in_path("nix-store") else {
        return false;
    };
    let Ok(output) = Command::new(nix_store)
        .args(["--query", "--roots", store_path])
        .stderr(Stdio::null())
        .output()
    else {
        return false;
    };
    if !output.status.success() {
        return false;
    }
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .any(|line| line == gc_root_path)
}

fn find_in_path(command: &str) -> Option<PathBuf> {
    if command.contains('/') {
        let path = PathBuf::from(command);
        return path.exists().then_some(path);
    }
    env::var_os("PATH").and_then(|path| {
        env::split_paths(&path)
            .map(|dir| dir.join(command))
            .find(|path| path.is_file())
    })
}

const PODMAN_LABEL_KEY: &str = "proxnix.managed";

fn reconcile_podman_secrets_main(args: &[String]) -> Result<(), String> {
    let mut rootfs: Option<PathBuf> = None;
    let mut vmid: Option<String> = None;
    let mut secrets_dir: Option<PathBuf> = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--rootfs" => {
                index += 1;
                rootfs = args.get(index).map(PathBuf::from);
            }
            "--vmid" => {
                index += 1;
                vmid = args.get(index).cloned();
            }
            "--secrets-dir" => {
                index += 1;
                secrets_dir = args.get(index).map(PathBuf::from);
            }
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            other => return Err(format!("unknown podman-secrets argument: {other}")),
        }
        index += 1;
    }

    reconcile_podman_secrets(
        &rootfs.ok_or("--rootfs is required")?,
        &vmid.ok_or("--vmid is required")?,
        &secrets_dir.ok_or("--secrets-dir is required")?,
    )
    .map_err(|err| format!("failed to reconcile Podman secrets: {err}"))
}

fn reconcile_podman_secrets(rootfs: &Path, vmid: &str, secrets_dir: &Path) -> io::Result<()> {
    let live_names = if secrets_dir.is_dir() {
        top_level_yaml_keys(&secrets_dir.join("effective.sops.yaml"))?
    } else {
        BTreeSet::new()
    };

    let secrets_json_path = rootfs.join("var/lib/containers/storage/secrets/secrets.json");
    let ids_dir = rootfs.join("etc/secrets/.ids");

    fs::create_dir_all(&ids_dir)?;
    let secrets_json_dir = secrets_json_path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "secrets.json has no parent"))?;
    fs::create_dir_all(secrets_json_dir)?;
    set_mode(secrets_json_dir, 0o700)?;

    let mut data = load_json_object(&secrets_json_path);
    ensure_object_field(&mut data, "secrets");
    ensure_object_field(&mut data, "nameToID");
    ensure_object_field(&mut data, "idToName");

    let now = utc_now_isoformat();
    let mut changed = false;

    let stale_ids = data
        .get("secrets")
        .and_then(Value::as_object)
        .map(|secrets| {
            secrets
                .iter()
                .filter_map(|(sid, entry)| {
                    let entry = entry.as_object()?;
                    let labels = entry.get("labels")?.as_object()?;
                    let managed =
                        labels.get(PODMAN_LABEL_KEY).and_then(Value::as_str) == Some("true");
                    let name = entry.get("name").and_then(Value::as_str).unwrap_or("");
                    if managed && !live_names.contains(name) {
                        Some((sid.clone(), name.to_owned()))
                    } else {
                        None
                    }
                })
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    for (sid, name) in stale_ids {
        object_field_mut(&mut data, "secrets").remove(&sid);
        object_field_mut(&mut data, "nameToID").remove(&name);
        object_field_mut(&mut data, "idToName").remove(&sid);
        match fs::remove_file(ids_dir.join(&sid)) {
            Ok(()) => {}
            Err(err) if err.kind() == io::ErrorKind::NotFound => {}
            Err(err) => return Err(err),
        }
        eprintln!("[proxnix-mount][{vmid}] Unregistered removed secret: {name}");
        changed = true;
    }

    for name in &live_names {
        let sid = podman_secret_id(vmid, name);
        let created_at = data
            .get("secrets")
            .and_then(Value::as_object)
            .and_then(|secrets| secrets.get(&sid))
            .and_then(Value::as_object)
            .and_then(|entry| entry.get("createdAt"))
            .and_then(Value::as_str)
            .unwrap_or(&now)
            .to_owned();

        let entry = json!({
            "name": name,
            "id": sid,
            "labels": { PODMAN_LABEL_KEY: "true" },
            "metadata": {},
            "createdAt": created_at,
            "updatedAt": now,
            "driver": "shell",
            "driverOptions": podman_driver_options(),
        });

        if data
            .get("secrets")
            .and_then(Value::as_object)
            .and_then(|secrets| secrets.get(&sid))
            != Some(&entry)
        {
            object_field_mut(&mut data, "secrets").insert(sid.clone(), entry);
            changed = true;
        }

        if data
            .get("nameToID")
            .and_then(Value::as_object)
            .and_then(|name_to_id| name_to_id.get(name))
            != Some(&json!(sid.clone()))
        {
            object_field_mut(&mut data, "nameToID").insert(name.clone(), json!(sid.clone()));
            changed = true;
        }
        if data
            .get("idToName")
            .and_then(Value::as_object)
            .and_then(|id_to_name| id_to_name.get(&sid))
            != Some(&json!(name))
        {
            object_field_mut(&mut data, "idToName").insert(sid.clone(), json!(name));
            changed = true;
        }

        let ids_file = ids_dir.join(&sid);
        if fs::read_to_string(&ids_file)
            .map(|existing| existing != *name)
            .unwrap_or(true)
        {
            fs::write(&ids_file, name)?;
            set_mode(&ids_file, 0o640)?;
        }
    }

    if changed {
        let tmp_path = secrets_json_path.with_file_name(format!(
            ".{}.tmp.{}",
            secrets_json_path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("secrets.json"),
            process::id()
        ));
        let rendered = serde_json::to_string_pretty(&Value::Object(data))
            .map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))?
            + "\n";
        fs::write(&tmp_path, rendered)?;
        set_mode(&tmp_path, 0o600)?;
        fs::rename(&tmp_path, &secrets_json_path)?;
        eprintln!(
            "[proxnix-mount][{vmid}] Podman secrets.json reconciled ({} secret(s))",
            live_names.len()
        );
    }

    Ok(())
}

fn top_level_yaml_keys(path: &Path) -> io::Result<BTreeSet<String>> {
    if !path.exists() {
        return Ok(BTreeSet::new());
    }

    let mut keys = BTreeSet::new();
    for line in fs::read_to_string(path)?.lines() {
        if line.is_empty() || line.starts_with(char::is_whitespace) || !line.contains(':') {
            continue;
        }
        let Some((key, _)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim();
        if !key.is_empty() && key != "sops" {
            keys.insert(key.to_owned());
        }
    }
    Ok(keys)
}

fn podman_secret_id(vmid: &str, name: &str) -> String {
    Uuid::new_v5(
        &Uuid::NAMESPACE_DNS,
        format!("proxnix:{vmid}:{name}").as_bytes(),
    )
    .simple()
    .to_string()
}

fn podman_driver_options() -> Value {
    json!({
        "store": "/var/lib/proxnix/runtime/bin/proxnix-secrets podman store",
        "lookup": "/var/lib/proxnix/runtime/bin/proxnix-secrets podman lookup",
        "list": "/var/lib/proxnix/runtime/bin/proxnix-secrets podman list",
        "delete": "/var/lib/proxnix/runtime/bin/proxnix-secrets podman delete",
    })
}

fn load_json_object(path: &Path) -> Map<String, Value> {
    fs::read_to_string(path)
        .ok()
        .and_then(|content| serde_json::from_str::<Value>(&content).ok())
        .and_then(|value| value.as_object().cloned())
        .unwrap_or_default()
}

fn ensure_object_field(data: &mut Map<String, Value>, field: &str) {
    if !data.get(field).is_some_and(Value::is_object) {
        data.insert(field.to_owned(), Value::Object(Map::new()));
    }
}

fn object_field_mut<'a>(
    data: &'a mut Map<String, Value>,
    field: &str,
) -> &'a mut Map<String, Value> {
    data.get_mut(field)
        .and_then(Value::as_object_mut)
        .expect("object field was initialized")
}

fn set_mode(path: &Path, mode: u32) -> io::Result<()> {
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
}

fn utc_now_isoformat() -> String {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    isoformat_from_unix_parts(now.as_secs() as i64, now.subsec_micros())
}

fn utc_now_seconds_z() -> String {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    zulu_seconds_from_unix(now.as_secs() as i64)
}

fn isoformat_from_unix_parts(seconds: i64, micros: u32) -> String {
    let days = seconds.div_euclid(86_400);
    let seconds_of_day = seconds.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let hour = seconds_of_day / 3_600;
    let minute = (seconds_of_day % 3_600) / 60;
    let second = seconds_of_day % 60;
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}.{micros:06}+00:00")
}

fn zulu_seconds_from_unix(seconds: i64) -> String {
    let days = seconds.div_euclid(86_400);
    let seconds_of_day = seconds.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let hour = seconds_of_day / 3_600;
    let minute = (seconds_of_day % 3_600) / 60;
    let second = seconds_of_day % 60;
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

fn civil_from_days(days_since_epoch: i64) -> (i64, i64, i64) {
    let z = days_since_epoch + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = mp + if mp < 10 { 3 } else { -9 };
    let year = y + if month <= 2 { 1 } else { 0 };
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::symlink;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Mutex;

    static TEMP_COUNTER: AtomicUsize = AtomicUsize::new(0);
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    struct TestTemp {
        path: PathBuf,
    }

    impl TestTemp {
        fn new() -> Self {
            let path = env::temp_dir().join(format!(
                "proxnix-host-test-{}-{}",
                process::id(),
                TEMP_COUNTER.fetch_add(1, Ordering::SeqCst)
            ));
            let _ = fs::remove_dir_all(&path);
            fs::create_dir_all(&path).unwrap();
            Self { path }
        }

        fn path(&self) -> &Path {
            &self.path
        }
    }

    impl Drop for TestTemp {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    fn setup_podman_test(tmp: &Path, sops_yaml: Option<&str>) -> (PathBuf, PathBuf) {
        let rootfs = tmp.join("rootfs");
        let secrets_dir = tmp.join("secrets");
        fs::create_dir_all(rootfs.join("etc/secrets")).unwrap();
        fs::create_dir_all(&secrets_dir).unwrap();
        if let Some(sops_yaml) = sops_yaml {
            fs::write(secrets_dir.join("effective.sops.yaml"), sops_yaml).unwrap();
        }
        (rootfs, secrets_dir)
    }

    #[test]
    fn parses_pve_config_fields_used_by_guest_module() {
        let data = parse_pve_conf_content(
            "\
# comment
ostype: nixos
hostname: ct101
nameserver: 1.1.1.1 8.8.8.8
searchdomain: example.test
ssh-public-keys: ssh-ed25519%20AAA%20root%40host%5Cn%23ignored%5Cnssh-rsa%20BBB
[pending]
memory: 2048
",
        );

        assert_eq!(
            data,
            ProxmoxNixData {
                hostname: Some("ct101".to_owned()),
                nameservers: vec!["1.1.1.1".to_owned(), "8.8.8.8".to_owned()],
                search_domain: Some("example.test".to_owned()),
                ssh_keys: vec![
                    "ssh-ed25519 AAA root@host".to_owned(),
                    "ssh-rsa BBB".to_owned()
                ],
            }
        );
    }

    #[test]
    fn renders_the_same_nix_shape_as_the_python_helper() {
        let rendered = generate_proxmox_nix(&ProxmoxNixData {
            hostname: Some("ct${101}".to_owned()),
            nameservers: vec!["1.1.1.1".to_owned(), "8.8.8.8".to_owned()],
            search_domain: Some("example.test".to_owned()),
            ssh_keys: vec!["ssh-ed25519 AAA \"quoted\"".to_owned()],
        });

        assert_eq!(
            rendered,
            "\
# Generated by pve-conf-to-nix.py \u{2014} do not edit by hand.
{ lib, ... }: {
  networking.hostName = lib.mkForce \"ct\\${101}\";
  networking.nameservers = lib.mkForce [ \"1.1.1.1\" \"8.8.8.8\" ];
  networking.search = lib.mkForce [ \"example.test\" ];
  users.users.root.openssh.authorizedKeys.keys = lib.mkForce [ \"ssh-ed25519 AAA \\\"quoted\\\"\" ];
}
"
        );
    }

    #[test]
    fn formats_utc_iso_timestamps_with_python_compatible_offset() {
        assert_eq!(
            isoformat_from_unix_parts(0, 123),
            "1970-01-01T00:00:00.000123+00:00"
        );
        assert_eq!(
            isoformat_from_unix_parts(1_704_067_199, 999_999),
            "2023-12-31T23:59:59.999999+00:00"
        );
        assert_eq!(zulu_seconds_from_unix(0), "1970-01-01T00:00:00Z");
    }

    #[test]
    fn initializes_reconciler_state_schema() {
        let tmp = TestTemp::new();
        let db = tmp.path().join("state/reconciler.sqlite");
        let conn = connect_state_db(&db).unwrap();

        init_state_db(&conn).unwrap();

        let tables = conn
            .prepare("select name from sqlite_master where type = 'table'")
            .unwrap()
            .query_map([], |row| row.get::<_, String>(0))
            .unwrap()
            .collect::<rusqlite::Result<BTreeSet<_>>>()
            .unwrap();
        assert!(tables.contains("container_observations"));
        assert!(tables.contains("closure_observations"));
        assert!(tables.contains("deployment_attempts"));
    }

    #[test]
    fn updates_container_observation_idempotently() {
        let tmp = TestTemp::new();
        let conn = connect_state_db(&tmp.path().join("reconciler.sqlite")).unwrap();

        observe_container(
            &conn,
            &ContainerObservation {
                vmid: 101,
                node: "pve1".to_owned(),
                desired_system: Some("/nix/store/desired-a".to_owned()),
                current_system: Some("/nix/store/current-a".to_owned()),
                container_is_local: true,
                last_phase: Some("observe".to_owned()),
                last_status: Some("noop-current".to_owned()),
                last_error: None,
            },
        )
        .unwrap();
        observe_container(
            &conn,
            &ContainerObservation {
                vmid: 101,
                node: "pve1".to_owned(),
                desired_system: Some("/nix/store/desired-a".to_owned()),
                current_system: Some("/nix/store/current-a".to_owned()),
                container_is_local: true,
                last_phase: Some("observe".to_owned()),
                last_status: Some("activated".to_owned()),
                last_error: None,
            },
        )
        .unwrap();

        let rows = conn
            .prepare("select vmid, last_status from container_observations")
            .unwrap()
            .query_map([], |row| {
                Ok((row.get::<_, i64>(0)?, row.get::<_, String>(1)?))
            })
            .unwrap()
            .collect::<rusqlite::Result<Vec<_>>>()
            .unwrap();
        assert_eq!(rows, vec![(101, "activated".to_owned())]);
    }

    #[test]
    fn records_closure_observation_with_explicit_gcroot_state() {
        let tmp = TestTemp::new();
        let conn = connect_state_db(&tmp.path().join("reconciler.sqlite")).unwrap();

        observe_closure(
            &conn,
            &ClosureObservation {
                store_path: "/nix/store/aaa-desired".to_owned(),
                host_has_closure: Some(true),
                container_has_closure: Some(false),
                protected_by_host_gc_root: Some(true),
                gc_root_path: Some("/var/lib/proxnix/gcroots/deploy/aaa-desired".to_owned()),
            },
        )
        .unwrap();

        let row = conn
            .query_row(
                "select store_path, host_has_closure, container_has_closure, protected_by_host_gc_root, gc_root_path from closure_observations",
                [],
                |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, i64>(1)?,
                        row.get::<_, i64>(2)?,
                        row.get::<_, i64>(3)?,
                        row.get::<_, String>(4)?,
                    ))
                },
            )
            .unwrap();
        assert_eq!(
            row,
            (
                "/nix/store/aaa-desired".to_owned(),
                1,
                0,
                1,
                "/var/lib/proxnix/gcroots/deploy/aaa-desired".to_owned(),
            )
        );
    }

    #[test]
    fn verifies_real_gcroot_for_closure_observation() {
        let _env_guard = ENV_LOCK.lock().unwrap();
        let tmp = TestTemp::new();
        let root = tmp.path();
        let conn = connect_state_db(&root.join("reconciler.sqlite")).unwrap();
        let fake_bin = root.join("bin");
        fs::create_dir_all(&fake_bin).unwrap();
        let store_path = "/nix/store/aaa-desired";
        let gcroot = root.join("gcroots/deploy/101-desired");
        fs::create_dir_all(gcroot.parent().unwrap()).unwrap();
        symlink(store_path, &gcroot).unwrap();
        let nix_store = fake_bin.join("nix-store");
        fs::write(
            &nix_store,
            format!(
                "\
#!/bin/sh
if [ \"$1\" = \"--query\" ] && [ \"$2\" = \"--roots\" ] && [ \"$3\" = \"{store_path}\" ]; then
  printf '%s\\n' \"{}\"
  exit 0
fi
exit 2
",
                gcroot.display()
            ),
        )
        .unwrap();
        set_mode(&nix_store, 0o755).unwrap();

        let old_path = env::var_os("PATH");
        env::set_var(
            "PATH",
            format!(
                "{}:{}",
                fake_bin.display(),
                old_path
                    .as_deref()
                    .and_then(|value| value.to_str())
                    .unwrap_or("")
            ),
        );
        observe_closure(
            &conn,
            &ClosureObservation {
                store_path: store_path.to_owned(),
                host_has_closure: Some(true),
                container_has_closure: Some(false),
                protected_by_host_gc_root: None,
                gc_root_path: Some(gcroot.display().to_string()),
            },
        )
        .unwrap();
        if let Some(old_path) = old_path {
            env::set_var("PATH", old_path);
        } else {
            env::remove_var("PATH");
        }

        let protected = conn
            .query_row(
                "select protected_by_host_gc_root from closure_observations",
                [],
                |row| row.get::<_, i64>(0),
            )
            .unwrap();
        assert_eq!(protected, 1);
    }

    #[test]
    fn records_deployment_attempts() {
        let tmp = TestTemp::new();
        let conn = connect_state_db(&tmp.path().join("reconciler.sqlite")).unwrap();

        let attempt_id = record_deployment_attempt(
            &conn,
            &DeploymentAttempt {
                vmid: 101,
                store_path: Some("/nix/store/desired-a".to_owned()),
                phase: "seed".to_owned(),
                status: "ok".to_owned(),
                error: None,
                finished_at: Some("2026-01-01T00:00:00Z".to_owned()),
            },
        )
        .unwrap();

        assert_eq!(attempt_id, 1);
        let row = conn
            .query_row(
                "select vmid, store_path, phase, status, finished_at from deployment_attempts",
                [],
                |row| {
                    Ok((
                        row.get::<_, i64>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, String>(2)?,
                        row.get::<_, String>(3)?,
                        row.get::<_, String>(4)?,
                    ))
                },
            )
            .unwrap();
        assert_eq!(
            row,
            (
                101,
                "/nix/store/desired-a".to_owned(),
                "seed".to_owned(),
                "ok".to_owned(),
                "2026-01-01T00:00:00Z".to_owned(),
            )
        );
    }

    #[test]
    fn reconciles_podman_secrets_json_for_live_keys() {
        let tmp = TestTemp::new();
        let (rootfs, secrets_dir) = setup_podman_test(
            tmp.path(),
            Some("alpha: ENC[a]\nbeta: ENC[b]\nsops:\n    version: 3\n"),
        );

        reconcile_podman_secrets(&rootfs, "101", &secrets_dir).unwrap();

        let secrets_json = rootfs.join("var/lib/containers/storage/secrets/secrets.json");
        assert!(secrets_json.exists());
        let data: Value = serde_json::from_str(&fs::read_to_string(secrets_json).unwrap()).unwrap();
        let secrets = data["secrets"].as_object().unwrap();
        let names = secrets
            .values()
            .map(|entry| entry["name"].as_str().unwrap().to_owned())
            .collect::<BTreeSet<_>>();
        assert_eq!(
            names,
            BTreeSet::from(["alpha".to_owned(), "beta".to_owned()])
        );
        for entry in secrets.values() {
            assert_eq!(entry["labels"], json!({ "proxnix.managed": "true" }));
            assert_eq!(entry["driver"], "shell");
            assert_eq!(entry["driverOptions"], podman_driver_options());
        }

        let ids_dir = rootfs.join("etc/secrets/.ids");
        let ids = fs::read_dir(ids_dir)
            .unwrap()
            .map(|entry| fs::read_to_string(entry.unwrap().path()).unwrap())
            .collect::<BTreeSet<_>>();
        assert_eq!(ids, BTreeSet::from(["alpha".to_owned(), "beta".to_owned()]));
    }

    #[test]
    fn reconciles_podman_secrets_json_by_removing_stale_managed_entries() {
        let tmp = TestTemp::new();
        let (rootfs, secrets_dir) =
            setup_podman_test(tmp.path(), Some("alpha: ENC[a]\nsops:\n    version: 3\n"));

        reconcile_podman_secrets(&rootfs, "101", &secrets_dir).unwrap();
        fs::write(
            secrets_dir.join("effective.sops.yaml"),
            "beta: ENC[b]\nsops:\n    version: 3\n",
        )
        .unwrap();
        reconcile_podman_secrets(&rootfs, "101", &secrets_dir).unwrap();

        let data: Value = serde_json::from_str(
            &fs::read_to_string(rootfs.join("var/lib/containers/storage/secrets/secrets.json"))
                .unwrap(),
        )
        .unwrap();
        let names = data["secrets"]
            .as_object()
            .unwrap()
            .values()
            .map(|entry| entry["name"].as_str().unwrap().to_owned())
            .collect::<BTreeSet<_>>();
        assert_eq!(names, BTreeSet::from(["beta".to_owned()]));

        let ids = fs::read_dir(rootfs.join("etc/secrets/.ids"))
            .unwrap()
            .map(|entry| fs::read_to_string(entry.unwrap().path()).unwrap())
            .collect::<BTreeSet<_>>();
        assert_eq!(ids, BTreeSet::from(["beta".to_owned()]));
    }

    #[test]
    fn reconciles_podman_secrets_json_without_touching_unmanaged_entries() {
        let tmp = TestTemp::new();
        let (rootfs, secrets_dir) =
            setup_podman_test(tmp.path(), Some("alpha: ENC[a]\nsops:\n    version: 3\n"));
        let secrets_json = rootfs.join("var/lib/containers/storage/secrets/secrets.json");
        fs::create_dir_all(secrets_json.parent().unwrap()).unwrap();
        fs::write(
            &secrets_json,
            serde_json::to_string(&json!({
                "secrets": {
                    "deadbeef": {
                        "name": "manual",
                        "id": "deadbeef",
                        "labels": { "foo": "bar" },
                        "driver": "file",
                    }
                },
                "nameToID": { "manual": "deadbeef" },
                "idToName": { "deadbeef": "manual" },
            }))
            .unwrap(),
        )
        .unwrap();

        reconcile_podman_secrets(&rootfs, "101", &secrets_dir).unwrap();

        let data: Value = serde_json::from_str(&fs::read_to_string(secrets_json).unwrap()).unwrap();
        assert!(data["secrets"]
            .as_object()
            .unwrap()
            .contains_key("deadbeef"));
        let names = data["secrets"]
            .as_object()
            .unwrap()
            .values()
            .map(|entry| entry["name"].as_str().unwrap().to_owned())
            .collect::<BTreeSet<_>>();
        assert_eq!(
            names,
            BTreeSet::from(["alpha".to_owned(), "manual".to_owned()])
        );
    }
}
