use std::collections::HashMap;
use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    if let Err(err) = run(env::args().collect()) {
        eprintln!("error: {err}");
        std::process::exit(1);
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    match args.get(1).map(String::as_str) {
        Some("pve-conf-to-nix") => pve_conf_to_nix_main(&args[2..]),
        Some("-h") | Some("--help") | None => {
            print_usage();
            Ok(())
        }
        Some("-V") | Some("--version") => {
            println!("proxnix-host {}", version());
            Ok(())
        }
        Some(command) => Err(format!("unknown subcommand: {command}")),
    }
}

fn version() -> &'static str {
    option_env!("PROXNIX_VERSION").unwrap_or(env!("CARGO_PKG_VERSION"))
}

fn print_usage() {
    println!(
        "\
Usage:
  proxnix-host pve-conf-to-nix --pve-conf <path> --out-dir <dir>
  proxnix-host --version
"
    );
}

fn pve_conf_to_nix_main(args: &[String]) -> Result<(), String> {
    let mut pve_conf: Option<PathBuf> = None;
    let mut out_dir: Option<PathBuf> = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--pve-conf" => {
                index += 1;
                pve_conf = args.get(index).map(PathBuf::from);
            }
            "--out-dir" => {
                index += 1;
                out_dir = args.get(index).map(PathBuf::from);
            }
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            other => return Err(format!("unknown pve-conf-to-nix argument: {other}")),
        }
        index += 1;
    }

    let pve_conf = pve_conf.ok_or("--pve-conf is required")?;
    let out_dir = out_dir.ok_or("--out-dir is required")?;
    let rendered = generate_proxmox_nix(
        &parse_pve_conf(&pve_conf)
            .map_err(|err| format!("failed to read {}: {err}", pve_conf.display()))?,
    );

    fs::create_dir_all(&out_dir)
        .map_err(|err| format!("failed to create {}: {err}", out_dir.display()))?;
    write_if_changed(&out_dir.join("proxmox.nix"), &rendered).map_err(|err| {
        format!(
            "failed to write {}: {err}",
            out_dir.join("proxmox.nix").display()
        )
    })?;
    Ok(())
}

#[derive(Debug, Default, PartialEq, Eq)]
struct ProxmoxNixData {
    hostname: Option<String>,
    nameservers: Vec<String>,
    search_domain: Option<String>,
    ssh_keys: Vec<String>,
}

fn parse_pve_conf(path: &Path) -> io::Result<ProxmoxNixData> {
    let content = fs::read_to_string(path)?;
    Ok(parse_pve_conf_content(&content))
}

fn parse_pve_conf_content(content: &str) -> ProxmoxNixData {
    let mut raw = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
            continue;
        }
        let Some((key, value)) = line.split_once(": ") else {
            continue;
        };
        raw.insert(key.trim().to_owned(), value.trim().to_owned());
    }

    ProxmoxNixData {
        hostname: raw
            .get("hostname")
            .filter(|value| !value.is_empty())
            .cloned(),
        nameservers: raw
            .get("nameserver")
            .map(|value| value.split_whitespace().map(str::to_owned).collect())
            .unwrap_or_default(),
        search_domain: raw
            .get("searchdomain")
            .filter(|value| !value.is_empty())
            .cloned(),
        ssh_keys: decode_ssh_public_keys(raw.get("ssh-public-keys").map(String::as_str)),
    }
}

fn generate_proxmox_nix(data: &ProxmoxNixData) -> String {
    let mut lines = vec![
        format!(
            "# Generated by pve-conf-to-nix.py {} do not edit by hand.",
            '\u{2014}'
        ),
        "{ lib, ... }: {".to_owned(),
    ];

    if let Some(hostname) = &data.hostname {
        lines.push(format!(
            "  networking.hostName = lib.mkForce {};",
            nix_str(hostname)
        ));
    }
    if !data.nameservers.is_empty() {
        lines.push(format!(
            "  networking.nameservers = lib.mkForce {};",
            nix_str_list(&data.nameservers)
        ));
    }
    if let Some(search_domain) = &data.search_domain {
        lines.push(format!(
            "  networking.search = lib.mkForce [ {} ];",
            nix_str(search_domain)
        ));
    }
    if !data.ssh_keys.is_empty() {
        lines.push(format!(
            "  users.users.root.openssh.authorizedKeys.keys = lib.mkForce {};",
            nix_str_list(&data.ssh_keys)
        ));
    }

    lines.push("}".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if path.exists() && fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }
    fs::write(path, content)
}

fn decode_ssh_public_keys(raw_value: Option<&str>) -> Vec<String> {
    let Some(raw_value) = raw_value else {
        return Vec::new();
    };
    let decoded = percent_decode_lossy(raw_value).replace("\\n", "\n");
    decoded
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.trim_start().starts_with('#'))
        .map(str::to_owned)
        .collect()
}

fn percent_decode_lossy(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;

    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            if let (Some(high), Some(low)) =
                (hex_value(bytes[index + 1]), hex_value(bytes[index + 2]))
            {
                decoded.push((high << 4) | low);
                index += 3;
                continue;
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }

    String::from_utf8_lossy(&decoded).into_owned()
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

fn nix_str(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${");
    format!("\"{escaped}\"")
}

fn nix_str_list(items: &[String]) -> String {
    let rendered = items
        .iter()
        .map(|item| nix_str(item))
        .collect::<Vec<_>>()
        .join(" ");
    format!("[ {rendered} ]")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_pve_config_fields_used_by_guest_module() {
        let data = parse_pve_conf_content(
            "\
# comment
ostype: nixos
hostname: ct101
nameserver: 1.1.1.1 8.8.8.8
searchdomain: example.test
ssh-public-keys: ssh-ed25519%20AAA%20root%40host%5Cn%23ignored%5Cnssh-rsa%20BBB
[pending]
memory: 2048
",
        );

        assert_eq!(
            data,
            ProxmoxNixData {
                hostname: Some("ct101".to_owned()),
                nameservers: vec!["1.1.1.1".to_owned(), "8.8.8.8".to_owned()],
                search_domain: Some("example.test".to_owned()),
                ssh_keys: vec![
                    "ssh-ed25519 AAA root@host".to_owned(),
                    "ssh-rsa BBB".to_owned()
                ],
            }
        );
    }

    #[test]
    fn renders_the_same_nix_shape_as_the_python_helper() {
        let rendered = generate_proxmox_nix(&ProxmoxNixData {
            hostname: Some("ct${101}".to_owned()),
            nameservers: vec!["1.1.1.1".to_owned(), "8.8.8.8".to_owned()],
            search_domain: Some("example.test".to_owned()),
            ssh_keys: vec!["ssh-ed25519 AAA \"quoted\"".to_owned()],
        });

        assert_eq!(
            rendered,
            "\
# Generated by pve-conf-to-nix.py \u{2014} do not edit by hand.
{ lib, ... }: {
  networking.hostName = lib.mkForce \"ct\\${101}\";
  networking.nameservers = lib.mkForce [ \"1.1.1.1\" \"8.8.8.8\" ];
  networking.search = lib.mkForce [ \"example.test\" ];
  users.users.root.openssh.authorizedKeys.keys = lib.mkForce [ \"ssh-ed25519 AAA \\\"quoted\\\"\" ];
}
"
        );
    }
}
