# chezmoi.nix — Application config management via chezmoi.
#
# Boundary:
#   Nix  → OS, packages, services, systemd units, all declarative system state
#   THIS → application config files only, under a dedicated config root
#   Nix does NOT manage anything under configRoot.
#   chezmoi does NOT manage anything under /nix or Nix-generated paths.
#
# Enabled by default in base.nix so every LXC has the environment ready.
# Change review and apply remain intentionally manual (operator-driven).
#
# Operator workflow:
#   cfg diff          # inspect drift between source state and config root
#   cfg status        # summary of what would change
#   cfg apply         # reconcile config root from source state
#   cfg apply --dry-run
#
# The `cfg` wrapper runs chezmoi as the management user with the Nix-managed
# config file so no flags are needed at the call site.

{ config, lib, pkgs, ... }:

let
  cfg = config.proxnix.chezmoi;
in {

  options.proxnix.chezmoi = {

    enable = lib.mkEnableOption "chezmoi application config management";

    configRoot = lib.mkOption {
      type        = lib.types.str;
      default     = "/srv/config";
      description = lib.mdDoc ''
        Target directory tree where chezmoi manages application config files.
        Structure: `/srv/config/<app>/`.
        Services read from subdirectories here; they should not write back.
        This tree contains config only — no state, no data.
      '';
    };

    sourceDir = lib.mkOption {
      type        = lib.types.str;
      default     = "/var/lib/chezmoi/source";
      description = lib.mdDoc ''
        chezmoi source state directory. Must be persistent across reboots.
        Back it up or point it at a git clone via `bootstrapRepo`.
        Only the management user has access.
      '';
    };

    user = lib.mkOption {
      type        = lib.types.str;
      default     = "configmgr";
      description = lib.mdDoc ''
        System user that owns the source state and the config root.
        The `cfg` wrapper runs chezmoi as this user.
      '';
    };

    bootstrapRepo = lib.mkOption {
      type        = lib.types.nullOr lib.types.str;
      default     = null;
      example     = "git@github.com:you/chezmoi-configs.git";
      description = lib.mdDoc ''
        Optional git repository URL. When set, the activation script clones it
        into `sourceDir` on first boot — only if `sourceDir` is empty.
        Does not trigger automatic apply. Review with `cfg diff`, then apply
        manually with `cfg apply`.
      '';
    };

  };

  config = lib.mkIf cfg.enable (lib.mkMerge [

    # ── base config (always applied when enabled) ──────────────────────────

    {
      # chezmoi, git (for source management), and the `cfg` convenience wrapper.
      # The wrapper invokes chezmoi as the management user so the caller
      # (typically root) needs no extra flags.
      environment.systemPackages = [
        pkgs.chezmoi
        pkgs.git
        (pkgs.writeShellScriptBin "cfg" ''
          exec ${pkgs.util-linux}/bin/runuser -u ${cfg.user} -- \
            ${pkgs.chezmoi}/bin/chezmoi \
            --config /etc/chezmoi/chezmoi.toml \
            "$@"
        '')
      ];

      # Dedicated system user.  No login shell needed — `runuser` in the
      # wrapper handles privilege drop without an interactive session.
      users.users.${cfg.user} = {
        isSystemUser = true;
        group        = cfg.user;
        home         = "/var/lib/chezmoi";
        createHome   = false;   # created by activation script below
        description  = "chezmoi application config management";
        shell        = pkgs.bash;
      };
      users.groups.${cfg.user} = {};

      # Nix-managed chezmoi config.  Lives in /etc so it survives across
      # rebuilds without touching the user's home directory.
      # sourceDir / destDir are the only required keys; add chezmoi settings
      # here (e.g. diff.pager, merge.command) as needed.
      environment.etc."chezmoi/chezmoi.toml" = {
        mode = "0644";
        text = ''
          # Generated by NixOS — edit proxnix.chezmoi options in base.nix,
          # not this file directly.
          [chezmoi]
            sourceDir = "${cfg.sourceDir}"
            destDir   = "${cfg.configRoot}"
        '';
      };

      # Directory setup — runs after the `users` activation script so that
      # chown can resolve the username.
      system.activationScripts.chezmoi-dirs = lib.stringAfter [ "users" ] ''
        # Management user home — private
        mkdir -p /var/lib/chezmoi
        chown ${cfg.user}:${cfg.user} /var/lib/chezmoi
        chmod 750 /var/lib/chezmoi

        # Source state — private; contains the chezmoi-tracked config templates
        mkdir -p ${cfg.sourceDir}
        chown ${cfg.user}:${cfg.user} ${cfg.sourceDir}
        chmod 750 ${cfg.sourceDir}

        # Application config root — world-readable so service users can read
        # their configs; the management user owns it
        mkdir -p ${cfg.configRoot}
        chown ${cfg.user}:${cfg.user} ${cfg.configRoot}
        chmod 755 ${cfg.configRoot}
      '';
    }

    # ── optional git bootstrap ─────────────────────────────────────────────

    (lib.mkIf (cfg.bootstrapRepo != null) {
      # Clone once on first boot when sourceDir is empty.
      # Non-destructive: if sourceDir already has content (e.g. after a
      # rebuild or container migration) the clone is skipped entirely.
      # Apply remains a manual step — run `cfg diff` first.
      system.activationScripts.chezmoi-bootstrap =
        lib.stringAfter [ "chezmoi-dirs" ] ''
          if [ -z "$(ls -A ${cfg.sourceDir} 2>/dev/null)" ]; then
            echo "chezmoi: cloning source from ${cfg.bootstrapRepo}" >&2
            ${pkgs.util-linux}/bin/runuser -u ${cfg.user} -- \
              ${pkgs.git}/bin/git clone \
                "${cfg.bootstrapRepo}" \
                "${cfg.sourceDir}" >&2
          fi
        '';
    })

  ]);

}
