{ config, lib, pkgs, ... }:

let
  cfg = config.proxnix.etckeeper;

  defaultIgnorePatterns = [
    "/nixos/configuration.nix"
    "/nixos/managed/"
    "/nixos/dropins/"
    "/proxnix/current-config-hash"
    "/proxnix/applied-config-hash"
    "/proxnix/vmid"
    "/proxnix/proxnix-apply-config-runner"
    "/systemd/system.attached/"
    "/age/identity.txt"
    "/age/shared_identity.txt"
    "/secrets/"
    "/ssh/ssh_host_*"
    "/machine-id"
    "/adjtime"
    "/hostname"
    "/hosts"
    "/resolv.conf"
    "/mtab"
    "/passwd"
    "/passwd-"
    "/group"
    "/group-"
    "/shadow"
    "/shadow-"
    "/gshadow"
    "/gshadow-"
    "/subuid"
    "/subuid-"
    "/subgid"
    "/subgid-"
  ];

  gitignoreText =
    lib.concatStringsSep "\n" (
      [
        "# Generated by NixOS — edit proxnix.etckeeper options in base.nix."
        "# Ignore proxnix-rendered state, volatile machine files, and secrets."
        ""
      ]
      ++ defaultIgnorePatterns
      ++ cfg.extraIgnorePatterns
    )
    + "\n";

  gitattributesText =
    lib.concatStringsSep "\n" (
      [
        "# Generated by NixOS — keep secrets opaque and diffs readable."
        "*.age binary"
        "*.key -diff"
        "*.pem -diff"
        "*.p12 -diff"
        "shadow -diff"
        "gshadow -diff"
        "ssh/ssh_host_* -diff"
        ""
      ]
      ++ cfg.extraGitAttributes
    )
    + "\n";

  staticExcludeText =
    lib.concatStringsSep "\n" (
      [
        "# Generated by NixOS — ignore current /etc symlinks into /nix/store."
        "# Regenerated on activation; add exceptions via"
        "# proxnix.etckeeper.keepStoreLinkedPaths."
        ""
      ]
    )
    + "\n";

  etckeeperConfText = ''
    # Generated by NixOS — edit proxnix.etckeeper options in base.nix.
    VCS="git"
  '';

  remoteValue = if cfg.remote == null then "" else cfg.remote;
in {

  options.proxnix.etckeeper = {
    enable = lib.mkEnableOption "etckeeper-backed tracking of guest-local /etc drift";

    branch = lib.mkOption {
      type = lib.types.str;
      default = "main";
      description = lib.mdDoc ''
        Initial branch name used when etckeeper creates `/etc/.git`.
      '';
    };

    remote = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "git@github.com:you/container-etc.git";
      description = lib.mdDoc ''
        Optional Git remote URL to register as `origin` for `/etc/.git`.
        It is added only when the repo has no existing `origin`.
      '';
    };

    gitUserName = lib.mkOption {
      type = lib.types.str;
      default = "proxnix etckeeper";
      description = lib.mdDoc ''
        Git author name configured for `/etc/.git`.
      '';
    };

    gitUserEmail = lib.mkOption {
      type = lib.types.str;
      default = "root@proxnix.invalid";
      description = lib.mdDoc ''
        Git author email configured for `/etc/.git`.
      '';
    };

    autoCommit = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = lib.mdDoc ''
        Whether to run a periodic etckeeper commit when `/etc` has drift.
      '';
    };

    autoCommitOnCalendar = lib.mkOption {
      type = lib.types.str;
      default = "daily";
      description = lib.mdDoc ''
        `systemd.timer` schedule for the automatic etckeeper snapshot job.
      '';
    };

    extraIgnorePatterns = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "/wireguard/" "!/wireguard/public.key" ];
      description = lib.mdDoc ''
        Extra `.gitignore` patterns appended to `/etc/.gitignore`.
        Negative patterns (for example `!/path`) can be used to re-include
        specific files.
      '';
    };

    extraGitAttributes = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "mycerts/*.crt diff" ];
      description = lib.mdDoc ''
        Extra `.gitattributes` rules appended to `/etc/.gitattributes`.
      '';
    };

    ignoreStoreLinkedPaths = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = lib.mdDoc ''
        Ignore paths in `/etc` that are symlinks resolving into `/nix/store`.
        This keeps etckeeper focused on guest-local drift instead of Nix-managed
        generation churn.
      '';
    };

    keepStoreLinkedPaths = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = [ "/ssl/certs/ca-certificates.crt" ];
      description = lib.mdDoc ''
        Absolute `/etc` paths to keep track of even when they are symlinks into
        `/nix/store`. Entries must be written relative to `/etc`, for example
        `/ssl/certs/ca-certificates.crt`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      pkgs.etckeeper
      pkgs.git
      (pkgs.writeShellScriptBin "etc" ''
        set -eu

        cmd="''${1:-status}"
        if [ "$#" -gt 0 ]; then
          shift
        fi

        case "$cmd" in
          init|commit|uninit|pre-install|post-install)
            exec ${pkgs.etckeeper}/bin/etckeeper "$cmd" "$@"
            ;;
          *)
            exec ${pkgs.etckeeper}/bin/etckeeper vcs "$cmd" "$@"
            ;;
        esac
      '')
    ];

    system.activationScripts.proxnix-etckeeper = lib.stringAfter [ "etc" ] ''
      set -eu

      repo_created=0

      mkdir -p /etc/etckeeper

      tmp_ignore="$(mktemp /tmp/proxnix-etckeeper-ignore-XXXXXX)"
      tmp_attr="$(mktemp /tmp/proxnix-etckeeper-attr-XXXXXX)"
      tmp_conf="$(mktemp /tmp/proxnix-etckeeper-conf-XXXXXX)"
      tmp_exclude="$(mktemp /tmp/proxnix-etckeeper-exclude-XXXXXX)"

      cat > "$tmp_ignore" <<'EOF'
${gitignoreText}
EOF

      cat > "$tmp_attr" <<'EOF'
${gitattributesText}
EOF

      cat > "$tmp_conf" <<'EOF'
${etckeeperConfText}
EOF

      cat > "$tmp_exclude" <<'EOF'
${staticExcludeText}
EOF

      if ! cmp -s "$tmp_ignore" /etc/.gitignore 2>/dev/null; then
        install -m 0644 "$tmp_ignore" /etc/.gitignore
      fi

      if ! cmp -s "$tmp_attr" /etc/.gitattributes 2>/dev/null; then
        install -m 0644 "$tmp_attr" /etc/.gitattributes
      fi

      if ! cmp -s "$tmp_conf" /etc/etckeeper/etckeeper.conf 2>/dev/null; then
        install -m 0644 "$tmp_conf" /etc/etckeeper/etckeeper.conf
      fi

      if [ "${if cfg.ignoreStoreLinkedPaths then "1" else "0"}" = 1 ]; then
        while IFS= read -r -d "" path; do
          rel="''${path#/etc}"
          rel="''${rel#/}"
          [ -n "$rel" ] || continue

          keep=0
${lib.concatMapStringsSep "\n" (path: ''
          if [ "/$rel" = "${path}" ]; then
            keep=1
          fi
'') cfg.keepStoreLinkedPaths}
          if [ "$keep" -eq 0 ] && target="$(${pkgs.coreutils}/bin/readlink -f "$path" 2>/dev/null)" && \
             [ "''${target#/nix/store/}" != "$target" ]; then
            printf '/%s\n' "$rel" >> "$tmp_exclude"
          fi
        done < <(${pkgs.findutils}/bin/find /etc -xdev -type l -print0 2>/dev/null)
      fi

      ${pkgs.coreutils}/bin/sort -u -o "$tmp_exclude" "$tmp_exclude"

      if [ ! -d /etc/.git ]; then
        ${pkgs.etckeeper}/bin/etckeeper init
        repo_created=1
      fi

      mkdir -p /etc/.git/info

      if ! cmp -s "$tmp_exclude" /etc/.git/info/exclude 2>/dev/null; then
        install -m 0644 "$tmp_exclude" /etc/.git/info/exclude
      fi

      rm -f "$tmp_ignore" "$tmp_attr" "$tmp_conf" "$tmp_exclude"

      ${pkgs.git}/bin/git -C /etc config user.name '${cfg.gitUserName}'
      ${pkgs.git}/bin/git -C /etc config user.email '${cfg.gitUserEmail}'
      ${pkgs.git}/bin/git -C /etc config init.defaultBranch '${cfg.branch}'

      if ! ${pkgs.git}/bin/git -C /etc rev-parse --verify HEAD >/dev/null 2>&1; then
        ${pkgs.git}/bin/git -C /etc symbolic-ref HEAD "refs/heads/${cfg.branch}" >/dev/null 2>&1 || true
      fi

      if [ -n '${remoteValue}' ] && ! ${pkgs.git}/bin/git -C /etc remote get-url origin >/dev/null 2>&1; then
        ${pkgs.git}/bin/git -C /etc remote add origin '${remoteValue}'
      fi

      if [ "$repo_created" -eq 1 ] && [ -n "$(${pkgs.git}/bin/git -C /etc status --porcelain --untracked-files=all 2>/dev/null || true)" ]; then
        ${pkgs.etckeeper}/bin/etckeeper commit 'Initialize /etc with proxnix etckeeper'
      fi
    '';

    systemd.services.proxnix-etckeeper-auto-commit = lib.mkIf cfg.autoCommit {
      description = "Periodic etckeeper snapshot for /etc";
      path = [ pkgs.etckeeper pkgs.git ];
      serviceConfig = {
        Type = "oneshot";
      };
      script = ''
        set -eu

        [ -d /etc/.git ] || exit 0

        if [ -n "$(${pkgs.git}/bin/git -C /etc status --porcelain --untracked-files=all)" ]; then
          ${pkgs.etckeeper}/bin/etckeeper commit 'auto: snapshot /etc'
        fi
      '';
    };

    systemd.timers.proxnix-etckeeper-auto-commit = lib.mkIf cfg.autoCommit {
      description = "Schedule periodic etckeeper snapshots";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = cfg.autoCommitOnCalendar;
        Persistent = true;
        RandomizedDelaySec = "15m";
      };
    };
  };
}
