# Generated by yaml-to-nix.py from proxmox.yaml — do not edit by hand.
{ ... }: {
  networking.hostName = "example-container";
  networking.interfaces.eth0.ipv4.addresses = [{
    address = "192.0.2.10";
    prefixLength = 24;
  }];
  networking.defaultGateway = "192.0.2.1";
  networking.nameservers = [ "192.0.2.1" ];
}
