#!/usr/bin/env python3
"""Render proxmox.nix from /etc/pve/lxc/<vmid>.conf."""

import argparse
import os
import sys
import urllib.parse


def nix_str(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${") + '"'


def nix_str_list(items):
    return "[ " + " ".join(nix_str(item) for item in items) + " ]"


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            if fh.read() == content:
                return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def decode_ssh_public_keys(raw_value):
    if not raw_value:
        return []
    decoded = urllib.parse.unquote(str(raw_value)).replace("\\n", "\n")
    return [
        line.strip()
        for line in decoded.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def parse_pve_conf(path):
    raw = {}
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("["):
                continue
            if ": " not in line:
                continue
            key, _, value = line.partition(": ")
            raw[key.strip()] = value.strip()

    data = {}

    hostname = raw.get("hostname")
    if hostname:
        data["hostname"] = hostname

    nameservers = raw.get("nameserver", "").split()
    if nameservers:
        data["nameservers"] = nameservers

    search_domain = raw.get("searchdomain")
    if search_domain:
        data["search_domain"] = search_domain

    ssh_keys = decode_ssh_public_keys(raw.get("ssh-public-keys"))
    if ssh_keys:
        data["ssh_keys"] = ssh_keys

    return data


def generate_proxmox_nix(data):
    lines = [
        "# Generated by pve-conf-to-nix.py — do not edit by hand.",
        "{ lib, ... }: {",
    ]

    hostname = data.get("hostname")
    if hostname:
        lines.append(f"  networking.hostName = lib.mkForce {nix_str(hostname)};")

    nameservers = data.get("nameservers", [])
    if nameservers:
        lines.append(f"  networking.nameservers = lib.mkForce {nix_str_list(nameservers)};")

    search_domain = data.get("search_domain")
    if search_domain:
        lines.append(f"  networking.search = lib.mkForce [ {nix_str(search_domain)} ];")

    ssh_keys = data.get("ssh_keys", [])
    if ssh_keys:
        lines.append(f"  users.users.root.openssh.authorizedKeys.keys = lib.mkForce {nix_str_list(ssh_keys)};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Render proxmox.nix from a Proxmox LXC config.")
    parser.add_argument("--pve-conf", required=True, help="Path to /etc/pve/lxc/<vmid>.conf")
    parser.add_argument("--out-dir", required=True, help="Directory that will receive proxmox.nix")
    args = parser.parse_args()

    try:
        rendered = generate_proxmox_nix(parse_pve_conf(args.pve_conf))
        os.makedirs(args.out_dir, exist_ok=True)
        write_if_changed(os.path.join(args.out_dir, "proxmox.nix"), rendered)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
