use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

use crate::common::{
    default_node_name, set_mode, take_arg, HostResult, DEFAULT_PROXNIX_DIR, DEFAULT_PVE_LXC_DIR,
};
use crate::print_usage;
use crate::pve_conf::{
    decode_ssh_public_keys, generate_proxmox_nix_with_header, nix_str, parse_pve_conf_raw,
    ProxmoxNixData,
};

pub(crate) struct AuthorityContainerManifest {
    pub(crate) vmid: String,
    hostname: Option<String>,
    pve: Map<String, Value>,
    placement: Map<String, Value>,
}

pub(crate) fn render_main(args: &[String]) -> HostResult<()> {
    let mut root = PathBuf::from(DEFAULT_PROXNIX_DIR);
    let mut authority: Option<PathBuf> = None;
    let mut pve_lxc_dir = PathBuf::from(DEFAULT_PVE_LXC_DIR);
    let mut node_name = default_node_name();
    let mut print_manifest = false;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--root" => root = PathBuf::from(take_arg(args, &mut index, "--root")?),
            "--authority" => {
                authority = Some(PathBuf::from(take_arg(args, &mut index, "--authority")?))
            }
            "--pve-lxc-dir" => {
                pve_lxc_dir = PathBuf::from(take_arg(args, &mut index, "--pve-lxc-dir")?)
            }
            "--node-name" => node_name = take_arg(args, &mut index, "--node-name")?,
            "--print-manifest" => print_manifest = true,
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            other => return Err(format!("unknown authority render argument: {other}").into()),
        }
        index += 1;
    }

    let authority = authority.unwrap_or_else(|| root.join("authority"));
    let manifests = render_authority(&root, &authority, &pve_lxc_dir, &node_name)
        .map_err(|err| format!("failed to render authority: {err}"))?;
    if print_manifest {
        print!(
            "{}",
            fs::read_to_string(authority.join("node-manifest.nix"))
                .map_err(|err| format!("failed to read node manifest: {err}"))?
        );
    } else {
        println!(
            "rendered {} container(s) for node {} into {}",
            manifests.len(),
            node_name,
            authority.display()
        );
    }
    Ok(())
}

pub(crate) fn render_authority(
    root: &Path,
    authority: &Path,
    pve_lxc_dir: &Path,
    node_name: &str,
) -> io::Result<Vec<AuthorityContainerManifest>> {
    let modules = authority.join("modules");
    let authority_containers = authority.join("containers");
    let legacy_containers = root.join("containers");

    fs::create_dir_all(authority)?;
    fs::create_dir_all(&modules)?;
    fs::create_dir_all(&authority_containers)?;

    for filename in ["base.nix", "common.nix", "security-policy.nix"] {
        let source = root.join(filename);
        if !source.exists() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("required proxnix module missing: {}", source.display()),
            ));
        }
        copy_if_present(&source, &modules.join(filename))?;
    }

    let using_authority_inputs = authority.join("publish-revision.json").is_file()
        || (!legacy_containers.exists() && dir_has_entries(&authority_containers)?);
    let authority_site = authority.join("site.nix");
    let legacy_site = root.join("site.nix");
    let has_site = if using_authority_inputs {
        authority_site.exists()
    } else if legacy_site.exists() {
        copy_if_present(&legacy_site, &authority_site)?;
        true
    } else {
        remove_file_if_present(&authority_site)?;
        false
    };
    if !using_authority_inputs && !authority.join("flake.lock").exists() {
        copy_if_present(&root.join("flake.lock"), &authority.join("flake.lock"))?;
    }
    atomic_write(
        &modules.join("proxnix-guest-base.nix"),
        &[
            "# Generated by proxnix-host authority render; do not edit by hand.",
            "{ ... }: {",
            "  imports = [",
            "    ./base.nix",
            "    ./common.nix",
            "    ./security-policy.nix",
            "  ];",
            "  system.stateVersion = \"25.11\";",
            "}",
            "",
        ]
        .join("\n"),
        0o644,
    )?;

    let mut vmids = Vec::new();
    let source_containers = if using_authority_inputs {
        authority_containers.clone()
    } else {
        legacy_containers
    };
    if source_containers.exists() {
        for entry in fs::read_dir(&source_containers)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().into_owned();
            if entry.file_type()?.is_dir() && name.chars().all(|ch| ch.is_ascii_digit()) {
                vmids.push(name);
            }
        }
        vmids.sort();
    }

    let mut manifests = Vec::new();
    for vmid in &vmids {
        let pve_conf = pve_lxc_dir.join(format!("{vmid}.conf"));
        let raw = if pve_conf.exists() {
            parse_pve_conf_raw(&pve_conf)?
        } else {
            HashMap::new()
        };
        let container_source = source_containers.join(vmid);
        let container_out = authority_containers.join(vmid);
        let dropin_names = sync_container_authority_inputs(
            &container_source,
            &container_out,
            &source_containers.join("_template"),
        )?;

        atomic_write(
            &container_out.join("proxmox.nix"),
            &authority_proxmox_module(&raw),
            0o644,
        )?;
        atomic_write(
            &container_out.join("modules.nix"),
            &render_modules_nix(has_site, &dropin_names),
            0o644,
        )?;

        let observed_pve_config = pve_conf.exists();
        let mut placement = Map::new();
        placement.insert("local".to_owned(), Value::Bool(true));
        placement.insert(
            "node".to_owned(),
            if observed_pve_config {
                Value::String(node_name.to_owned())
            } else {
                Value::Null
            },
        );
        if !observed_pve_config {
            placement.insert("targetNode".to_owned(), Value::String(node_name.to_owned()));
        }
        placement.insert(
            "observedPveConfig".to_owned(),
            Value::Bool(observed_pve_config),
        );
        manifests.push(AuthorityContainerManifest {
            vmid: vmid.clone(),
            hostname: raw.get("hostname").cloned(),
            pve: normalize_pve(&raw),
            placement,
        });
    }
    if source_containers != authority_containers {
        prune_unlisted_dirs(&authority_containers, &vmids.iter().cloned().collect())?;
    }

    atomic_write(
        &authority.join("flake.nix"),
        &render_authority_flake(node_name),
        0o644,
    )?;
    atomic_write(
        &authority.join("node-manifest.nix"),
        &render_node_manifest(node_name, &manifests, load_source_revision(root, authority)),
        0o644,
    )?;
    Ok(manifests)
}

fn sync_container_authority_inputs(
    source: &Path,
    out: &Path,
    template_root: &Path,
) -> io::Result<Vec<String>> {
    fs::create_dir_all(out)?;
    if source != out {
        sync_dropins(&source.join("dropins"), &out.join("dropins"))?;
        sync_runtime_scripts(&source.join("dropins"), &out.join("runtime-bin"))?;
        sync_selected_templates(
            &source.join("templates"),
            template_root,
            &out.join("_template"),
        )?;
    }
    list_module_dropins(&out.join("dropins"))
}

fn sync_dropins(source: &Path, dest: &Path) -> io::Result<()> {
    replace_dir(dest)?;
    if !source.is_dir() {
        fs::create_dir_all(dest)?;
        return Ok(());
    }
    fs::create_dir_all(dest)?;
    for entry in sorted_entries(source)? {
        let source_path = entry.path();
        let name = entry.file_name();
        if entry.file_type()?.is_file() {
            match source_path.extension().and_then(|ext| ext.to_str()) {
                Some("nix") => {
                    fs::copy(&source_path, dest.join(&name))?;
                }
                Some("service") => {
                    return Err(invalid_data(&format!(
                        "host-side dropins/*.service are no longer supported: {}",
                        source_path.display()
                    )));
                }
                Some("sh") | Some("py") => {}
                Some("container" | "volume" | "network" | "pod" | "image" | "build") => {
                    return Err(invalid_data(&format!(
                        "raw Quadlet drop-ins are no longer supported: {}",
                        source_path.display()
                    )));
                }
                _ => {}
            }
        } else if entry.file_type()?.is_dir() {
            copy_dir_recursive(&source_path, &dest.join(&name))?;
        }
    }
    Ok(())
}

fn sync_runtime_scripts(source_dropins: &Path, dest: &Path) -> io::Result<()> {
    replace_dir(dest)?;
    if !source_dropins.is_dir() {
        return Ok(());
    }
    let mut copied = false;
    for entry in sorted_entries(source_dropins)? {
        let source_path = entry.path();
        if !entry.file_type()?.is_file() {
            continue;
        }
        if matches!(
            source_path.extension().and_then(|ext| ext.to_str()),
            Some("sh" | "py")
        ) {
            fs::create_dir_all(dest)?;
            fs::copy(&source_path, dest.join(entry.file_name()))?;
            copied = true;
        }
    }
    if !copied && dest.exists() {
        fs::remove_dir_all(dest)?;
    }
    Ok(())
}

fn sync_selected_templates(
    selector_dir: &Path,
    template_root: &Path,
    dest: &Path,
) -> io::Result<()> {
    replace_dir(dest)?;
    if !selector_dir.is_dir() {
        return Ok(());
    }
    for selector in sorted_entries(selector_dir)? {
        let selector_path = selector.path();
        if !selector.file_type()?.is_file()
            || selector_path.extension().and_then(|ext| ext.to_str()) != Some("template")
        {
            continue;
        }
        let selector_name = selector.file_name().to_string_lossy().into_owned();
        let template_name = selector_name.trim_end_matches(".template");
        let source = template_root.join(template_name);
        if !source.is_dir() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("selected template not found: {}", source.display()),
            ));
        }
        copy_dir_recursive(&source, &dest.join(template_name))?;
    }
    Ok(())
}

fn list_module_dropins(dropins: &Path) -> io::Result<Vec<String>> {
    let mut names = Vec::new();
    if !dropins.is_dir() {
        return Ok(names);
    }
    for entry in sorted_entries(dropins)? {
        let path = entry.path();
        if !entry.file_type()?.is_file() {
            continue;
        }
        match path.extension().and_then(|ext| ext.to_str()) {
            Some("nix") => names.push(entry.file_name().to_string_lossy().into_owned()),
            Some("service") => {
                return Err(invalid_data(&format!(
                    "host-side dropins/*.service are no longer supported: {}",
                    path.display()
                )));
            }
            Some("container" | "volume" | "network" | "pod" | "image" | "build") => {
                return Err(invalid_data(&format!(
                    "raw Quadlet drop-ins are no longer supported: {}",
                    path.display()
                )));
            }
            _ => {}
        }
    }
    Ok(names)
}

fn replace_dir(path: &Path) -> io::Result<()> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    Ok(())
}

fn copy_dir_recursive(source: &Path, dest: &Path) -> io::Result<()> {
    fs::create_dir_all(dest)?;
    for entry in sorted_entries(source)? {
        let source_path = entry.path();
        let dest_path = dest.join(entry.file_name());
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            copy_dir_recursive(&source_path, &dest_path)?;
        } else if file_type.is_file() {
            fs::copy(&source_path, &dest_path)?;
        }
    }
    Ok(())
}

fn sorted_entries(path: &Path) -> io::Result<Vec<fs::DirEntry>> {
    let mut entries = fs::read_dir(path)?.collect::<io::Result<Vec<_>>>()?;
    entries.sort_by_key(|entry| entry.file_name());
    Ok(entries)
}

fn dir_has_entries(path: &Path) -> io::Result<bool> {
    if !path.is_dir() {
        return Ok(false);
    }
    Ok(fs::read_dir(path)?.next().is_some())
}

fn invalid_data(message: &str) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message)
}

fn normalize_pve(raw: &HashMap<String, String>) -> Map<String, Value> {
    let mut pve = Map::new();
    for key in ["ostype", "hostname", "rootfs", "net0", "features"] {
        if let Some(value) = raw.get(key).filter(|value| !value.is_empty()) {
            pve.insert(key.to_owned(), Value::String(value.clone()));
        }
    }
    for key in ["memory", "swap", "cores"] {
        if let Some(value) = raw.get(key).filter(|value| !value.is_empty()) {
            let rendered = value
                .parse::<i64>()
                .map(|number| Value::Number(number.into()))
                .unwrap_or_else(|_| Value::String(value.clone()));
            pve.insert(key.to_owned(), rendered);
        }
    }
    if let Some(unprivileged) = raw
        .get("unprivileged")
        .and_then(|value| parse_pve_bool(Some(value)))
    {
        pve.insert("unprivileged".to_owned(), Value::Bool(unprivileged));
    }
    pve
}

fn parse_pve_bool(raw: Option<&String>) -> Option<bool> {
    raw.map(|value| matches!(value.as_str(), "1" | "true" | "yes" | "on"))
}

fn authority_proxmox_module(raw: &HashMap<String, String>) -> String {
    let data = ProxmoxNixData {
        hostname: raw
            .get("hostname")
            .filter(|value| !value.is_empty())
            .cloned(),
        nameservers: raw
            .get("nameserver")
            .map(|value| value.split_whitespace().map(str::to_owned).collect())
            .unwrap_or_default(),
        search_domain: raw
            .get("searchdomain")
            .filter(|value| !value.is_empty())
            .cloned(),
        ssh_keys: decode_ssh_public_keys(raw.get("ssh-public-keys").map(String::as_str)),
    };
    generate_proxmox_nix_with_header(
        &data,
        "# Generated by proxnix-host authority render; do not edit by hand.",
    )
}

fn render_modules_nix(has_site: bool, dropins: &[String]) -> String {
    let mut lines = vec![
        "# Generated by proxnix-host authority render; do not edit by hand.".to_owned(),
        "let".to_owned(),
        "  site = ../../site.nix;".to_owned(),
        "in".to_owned(),
        "[".to_owned(),
        "  ../../modules/proxnix-guest-base.nix".to_owned(),
    ];
    if has_site {
        lines.push("] ++ (if builtins.pathExists site then [ site ] else []) ++ [".to_owned());
    } else {
        lines.push("] ++ [".to_owned());
    }
    lines.push("  ./proxmox.nix".to_owned());
    for dropin in dropins {
        lines.push(format!("  ./dropins/{dropin}"));
    }
    lines.push("]".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn render_pve_attrs(pve: &Map<String, Value>) -> String {
    if pve.is_empty() {
        return "{}".to_owned();
    }
    let mut lines = vec!["{".to_owned()];
    let mut keys = pve.keys().collect::<Vec<_>>();
    keys.sort();
    for key in keys {
        lines.push(format!(
            "      {} = {};",
            nix_attr_name(key),
            json_to_nix(&pve[key], 6)
        ));
    }
    lines.push("    }".to_owned());
    lines.join("\n")
}

fn render_node_manifest(
    node_name: &str,
    containers: &[AuthorityContainerManifest],
    source_revision: Option<Value>,
) -> String {
    let local_vmids = containers
        .iter()
        .filter(|container| container.placement.get("local").and_then(Value::as_bool) == Some(true))
        .map(|container| container.vmid.as_str())
        .collect::<Vec<_>>();
    let mut lines = vec![
        "# Generated by proxnix-host authority render; do not edit by hand.".to_owned(),
        "{ self, lib }:".to_owned(),
        "let".to_owned(),
        "  systemPath = name: builtins.unsafeDiscardStringContext \"${self.nixosConfigurations.${name}.config.system.build.toplevel}\";".to_owned(),
        "in {".to_owned(),
        format!("  nodeName = {};", nix_str(node_name)),
        "  vmids = [".to_owned(),
    ];
    for container in containers {
        lines.push(format!("    {}", nix_str(&container.vmid)));
    }
    lines.push("  ];".to_owned());
    lines.push("  localVmids = [".to_owned());
    for vmid in local_vmids {
        lines.push(format!("    {}", nix_str(vmid)));
    }
    lines.push("  ];".to_owned());
    lines.push("  containers = {".to_owned());

    let source = source_revision
        .as_ref()
        .map(|value| json_to_nix(value, 4))
        .unwrap_or_else(|| "null".to_owned());
    for container in containers {
        let hostname = container
            .hostname
            .clone()
            .unwrap_or_else(|| format!("ct{}", container.vmid));
        let system_attr = format!(
            "nixosConfigurations.ct{}.config.system.build.toplevel",
            container.vmid
        );
        lines.push(format!("    {} = {{", nix_attr_name(&container.vmid)));
        lines.push(format!("      vmid = {};", container.vmid));
        lines.push(format!("      hostname = {};", nix_str(&hostname)));
        lines.push(format!("      sourceRevision = {source};"));
        lines.push(format!("      systemAttr = {};", nix_str(&system_attr)));
        lines.push(format!(
            "      system = systemPath {};",
            nix_str(&format!("ct{}", container.vmid))
        ));
        lines.push(format!("      pve = {};", render_pve_attrs(&container.pve)));
        lines.push(format!(
            "      placement = {};",
            json_to_nix(&Value::Object(container.placement.clone()), 6)
        ));
        lines.push("    };".to_owned());
    }
    lines.push("  };".to_owned());
    lines.push("}".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn json_to_nix(value: &Value, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let inner = " ".repeat(indent + 2);
    match value {
        Value::Null => "null".to_owned(),
        Value::Bool(value) => {
            if *value {
                "true".to_owned()
            } else {
                "false".to_owned()
            }
        }
        Value::Number(value) => value.to_string(),
        Value::String(value) => nix_str(value),
        Value::Array(items) => {
            if items.is_empty() {
                "[]".to_owned()
            } else {
                format!(
                    "[ {} ]",
                    items
                        .iter()
                        .map(|item| json_to_nix(item, indent))
                        .collect::<Vec<_>>()
                        .join(" ")
                )
            }
        }
        Value::Object(map) => {
            if map.is_empty() {
                "{}".to_owned()
            } else {
                let mut lines = vec!["{".to_owned()];
                let mut keys = map.keys().collect::<Vec<_>>();
                keys.sort();
                for key in keys {
                    lines.push(format!(
                        "{inner}{} = {};",
                        nix_attr_name(key),
                        json_to_nix(&map[key], indent + 2)
                    ));
                }
                lines.push(format!("{pad}}}"));
                lines.join("\n")
            }
        }
    }
}

pub(crate) fn render_authority_flake(node_name: &str) -> String {
    let lines = vec![
        "# Generated by proxnix-host authority render; do not edit by hand.".to_owned(),
        "{".to_owned(),
        "  description = \"proxnix generated compatibility authority\";".to_owned(),
        String::new(),
        "  inputs.nixpkgs.url = \"github:NixOS/nixpkgs/nixos-25.11\";".to_owned(),
        "  inputs.nixpkgs-unstable.url = \"github:NixOS/nixpkgs/nixos-unstable\";".to_owned(),
        String::new(),
        "  outputs = { self, nixpkgs, nixpkgs-unstable }:".to_owned(),
        "    let".to_owned(),
        "      system = \"x86_64-linux\";".to_owned(),
        "      lib = nixpkgs.lib;".to_owned(),
        "      specialArgs = { inherit nixpkgs-unstable; };".to_owned(),
        "      manifest = import ./node-manifest.nix { inherit self lib; };".to_owned(),
        "      goldenTemplateModules =".to_owned(),
        "        [ ./modules/proxnix-guest-base.nix ]".to_owned(),
        "        ++ lib.optional (builtins.pathExists ./site.nix) ./site.nix;".to_owned(),
        "      mkCt = vmid: lib.nixosSystem {".to_owned(),
        "        inherit system;".to_owned(),
        "        inherit specialArgs;".to_owned(),
        "        modules = import ./containers/${vmid}/modules.nix;".to_owned(),
        "      };".to_owned(),
        "    in {".to_owned(),
        "      nixosConfigurations = {".to_owned(),
        "        proxnix-golden-template = lib.nixosSystem {".to_owned(),
        "          inherit system;".to_owned(),
        "          inherit specialArgs;".to_owned(),
        "          modules = goldenTemplateModules;".to_owned(),
        "        };".to_owned(),
        "      } // builtins.listToAttrs (map (vmid: {".to_owned(),
        "        name = \"ct${vmid}\";".to_owned(),
        "        value = mkCt vmid;".to_owned(),
        "      }) manifest.vmids);".to_owned(),
        String::new(),
        "      proxnix.containers = manifest.containers;".to_owned(),
        format!(
            "      proxnix.nodes.{} = manifest;",
            nix_attr_name(node_name)
        ),
        "    };".to_owned(),
        "}".to_owned(),
        String::new(),
    ];
    lines.join("\n")
}

fn load_source_revision(root: &Path, authority: &Path) -> Option<Value> {
    let path = authority.join("publish-revision.json");
    let fallback = root.join("publish-revision.json");
    let value = serde_json::from_str::<Value>(
        &fs::read_to_string(&path)
            .or_else(|_| fs::read_to_string(fallback))
            .ok()?,
    )
    .ok()?;
    value.is_object().then_some(value)
}

fn atomic_write(path: &Path, content: &str, mode: u32) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_file_name(format!(
        "{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("tmp")
    ));
    fs::write(&tmp, content)?;
    set_mode(&tmp, mode)?;
    fs::rename(tmp, path)
}

fn copy_if_present(source: &Path, dest: &Path) -> io::Result<bool> {
    if !source.exists() {
        return Ok(false);
    }
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(source, dest)?;
    Ok(true)
}

fn remove_file_if_present(path: &Path) -> io::Result<()> {
    if path.exists() || path.is_symlink() {
        fs::remove_file(path)?;
    }
    Ok(())
}

fn prune_unlisted_dirs(dir: &Path, keep: &BTreeSet<String>) -> io::Result<()> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if keep.contains(&name) {
            continue;
        }
        if entry.file_type()?.is_dir() {
            fs::remove_dir_all(entry.path())?;
        }
    }
    Ok(())
}

fn nix_attr_name(value: &str) -> String {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return nix_str(value);
    };
    let valid_first = first.is_ascii_alphabetic() || first == '_';
    let valid_rest = chars.all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '_' | '\'' | '-'));
    if valid_first && valid_rest {
        value.to_owned()
    } else {
        nix_str(value)
    }
}
