use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::common::HostResult;
use crate::print_usage;

pub(crate) fn main(args: &[String]) -> HostResult<()> {
    let mut pve_conf: Option<PathBuf> = None;
    let mut out_dir: Option<PathBuf> = None;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--pve-conf" => {
                index += 1;
                pve_conf = args.get(index).map(PathBuf::from);
            }
            "--out-dir" => {
                index += 1;
                out_dir = args.get(index).map(PathBuf::from);
            }
            "-h" | "--help" => {
                print_usage();
                return Ok(());
            }
            other => return Err(format!("unknown pve-conf-to-nix argument: {other}").into()),
        }
        index += 1;
    }

    let pve_conf = pve_conf.ok_or("--pve-conf is required")?;
    let out_dir = out_dir.ok_or("--out-dir is required")?;
    let rendered = generate_proxmox_nix(
        &parse_pve_conf(&pve_conf)
            .map_err(|err| format!("failed to read {}: {err}", pve_conf.display()))?,
    );

    fs::create_dir_all(&out_dir)
        .map_err(|err| format!("failed to create {}: {err}", out_dir.display()))?;
    write_if_changed(&out_dir.join("proxmox.nix"), &rendered).map_err(|err| {
        format!(
            "failed to write {}: {err}",
            out_dir.join("proxmox.nix").display()
        )
    })?;
    Ok(())
}

#[derive(Debug, Default, PartialEq, Eq)]
pub(crate) struct ProxmoxNixData {
    pub(crate) hostname: Option<String>,
    pub(crate) nameservers: Vec<String>,
    pub(crate) search_domain: Option<String>,
    pub(crate) ssh_keys: Vec<String>,
}

pub(crate) fn parse_pve_conf(path: &Path) -> io::Result<ProxmoxNixData> {
    let content = fs::read_to_string(path)?;
    Ok(parse_pve_conf_content(&content))
}

pub(crate) fn parse_pve_conf_content(content: &str) -> ProxmoxNixData {
    let raw = parse_pve_conf_raw_content(content);
    ProxmoxNixData {
        hostname: raw
            .get("hostname")
            .filter(|value| !value.is_empty())
            .cloned(),
        nameservers: raw
            .get("nameserver")
            .map(|value| value.split_whitespace().map(str::to_owned).collect())
            .unwrap_or_default(),
        search_domain: raw
            .get("searchdomain")
            .filter(|value| !value.is_empty())
            .cloned(),
        ssh_keys: decode_ssh_public_keys(raw.get("ssh-public-keys").map(String::as_str)),
    }
}

pub(crate) fn generate_proxmox_nix(data: &ProxmoxNixData) -> String {
    generate_proxmox_nix_with_header(
        data,
        &format!(
            "# Generated by proxnix-host pve-conf-to-nix {} do not edit by hand.",
            '\u{2014}'
        ),
    )
}

pub(crate) fn generate_proxmox_nix_with_header(data: &ProxmoxNixData, header: &str) -> String {
    let mut lines = vec![header.to_owned(), "{ lib, ... }: {".to_owned()];

    if let Some(hostname) = &data.hostname {
        lines.push(format!(
            "  networking.hostName = lib.mkForce {};",
            nix_str(hostname)
        ));
    }
    if !data.nameservers.is_empty() {
        lines.push(format!(
            "  networking.nameservers = lib.mkForce {};",
            nix_str_list(&data.nameservers)
        ));
    }
    if let Some(search_domain) = &data.search_domain {
        lines.push(format!(
            "  networking.search = lib.mkForce [ {} ];",
            nix_str(search_domain)
        ));
    }
    if !data.ssh_keys.is_empty() {
        lines.push(format!(
            "  users.users.root.openssh.authorizedKeys.keys = lib.mkForce {};",
            nix_str_list(&data.ssh_keys)
        ));
    }

    lines.push("}".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if path.exists() && fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }
    fs::write(path, content)
}

pub(crate) fn decode_ssh_public_keys(raw_value: Option<&str>) -> Vec<String> {
    let Some(raw_value) = raw_value else {
        return Vec::new();
    };
    let decoded = percent_decode_lossy(raw_value).replace("\\n", "\n");
    decoded
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.trim_start().starts_with('#'))
        .map(str::to_owned)
        .collect()
}

fn percent_decode_lossy(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;

    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            if let (Some(high), Some(low)) =
                (hex_value(bytes[index + 1]), hex_value(bytes[index + 2]))
            {
                decoded.push((high << 4) | low);
                index += 3;
                continue;
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }

    String::from_utf8_lossy(&decoded).into_owned()
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

pub(crate) fn nix_str(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${");
    format!("\"{escaped}\"")
}

fn nix_str_list(items: &[String]) -> String {
    let rendered = items
        .iter()
        .map(|item| nix_str(item))
        .collect::<Vec<_>>()
        .join(" ");
    format!("[ {rendered} ]")
}

pub(crate) fn parse_pve_conf_raw(path: &Path) -> io::Result<HashMap<String, String>> {
    Ok(parse_pve_conf_raw_content(&fs::read_to_string(path)?))
}

pub(crate) fn parse_pve_conf_raw_content(content: &str) -> HashMap<String, String> {
    let mut raw = HashMap::new();
    let mut in_top_level = true;
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_top_level = false;
            continue;
        }
        if !in_top_level || line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once(": ") else {
            continue;
        };
        raw.insert(key.trim().to_owned(), value.trim().to_owned());
    }
    raw
}

fn parse_pve_tags(raw_tags: Option<&str>) -> BTreeSet<String> {
    raw_tags
        .unwrap_or_default()
        .split(|ch: char| ch == ';' || ch == ',' || ch.is_whitespace())
        .map(str::trim)
        .filter(|tag| !tag.is_empty())
        .map(|tag| tag.to_ascii_lowercase())
        .collect()
}

fn pve_conf_tags(path: &Path) -> io::Result<BTreeSet<String>> {
    let raw = parse_pve_conf_raw(path)?;
    Ok(parse_pve_tags(raw.get("tags").map(String::as_str)))
}

pub(crate) fn pve_conf_has_tag(path: &Path, tag: &str) -> io::Result<bool> {
    Ok(pve_conf_tags(path)?.contains(&tag.to_ascii_lowercase()))
}

#[cfg(test)]
mod tests {
    use super::{parse_pve_conf_content, parse_pve_conf_raw_content, parse_pve_tags};

    #[test]
    fn parses_proxmox_tag_lists() {
        let tags = parse_pve_tags(Some("proxnix;nix-auto, nix-hold nix-stage"));
        assert!(tags.contains("proxnix"));
        assert!(tags.contains("nix-auto"));
        assert!(tags.contains("nix-hold"));
        assert!(tags.contains("nix-stage"));
    }

    #[test]
    fn raw_parser_ignores_pending_and_snapshot_sections() {
        let raw = parse_pve_conf_raw_content(
            "\
hostname: live
tags: proxnix;nix-auto

[pending]
hostname: pending
tags: nix-hold

[snapshot-before-upgrade]
hostname: snapshot
",
        );

        assert_eq!(raw.get("hostname").map(String::as_str), Some("live"));
        assert_eq!(
            raw.get("tags").map(String::as_str),
            Some("proxnix;nix-auto")
        );
    }

    #[test]
    fn proxmox_nix_data_uses_only_live_section() {
        let data = parse_pve_conf_content(
            "\
hostname: live
nameserver: 1.1.1.1 9.9.9.9

[pending]
hostname: pending
nameserver: 10.0.0.1
",
        );

        assert_eq!(data.hostname.as_deref(), Some("live"));
        assert_eq!(data.nameservers, vec!["1.1.1.1", "9.9.9.9"]);
    }
}
