import os
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PVE_CONF_TO_NIX = ROOT / "host" / "runtime" / "lib" / "pve-conf-to-nix.py"


def write_executable(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR)


class PveConfToNixTests(unittest.TestCase):
    def test_fallback_renderer_matches_expected_shape(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            pve_conf = root / "101.conf"
            out_dir = root / "out"
            pve_conf.write_text(
                "\n".join(
                    [
                        "hostname: ct${101}",
                        "nameserver: 1.1.1.1 8.8.8.8",
                        "searchdomain: example.test",
                        "ssh-public-keys: ssh-ed25519%20AAA%20root%40host%5Cn%23skip%5Cnssh-rsa%20BBB",
                        "",
                    ]
                ),
                encoding="utf-8",
            )

            env = os.environ.copy()
            env["PROXNIX_PVE_CONF_TO_NIX_FORCE_PYTHON"] = "1"
            result = subprocess.run(
                [
                    sys.executable,
                    str(PVE_CONF_TO_NIX),
                    "--pve-conf",
                    str(pve_conf),
                    "--out-dir",
                    str(out_dir),
                ],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                (out_dir / "proxmox.nix").read_text(encoding="utf-8"),
                """# Generated by pve-conf-to-nix.py \N{EM DASH} do not edit by hand.
{ lib, ... }: {
  networking.hostName = lib.mkForce "ct\\${101}";
  networking.nameservers = lib.mkForce [ "1.1.1.1" "8.8.8.8" ];
  networking.search = lib.mkForce [ "example.test" ];
  users.users.root.openssh.authorizedKeys.keys = lib.mkForce [ "ssh-ed25519 AAA root@host" "ssh-rsa BBB" ];
}
""",
            )

    def test_delegates_to_rust_host_binary_when_available(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fake_bin = root / "proxnix-host"
            marker = root / "args.txt"
            write_executable(
                fake_bin,
                f"""#!/bin/sh
printf '%s\\n' "$@" > '{marker}'
""",
            )

            env = os.environ.copy()
            env["PROXNIX_HOST_BIN"] = str(fake_bin)
            result = subprocess.run(
                [
                    sys.executable,
                    str(PVE_CONF_TO_NIX),
                    "--pve-conf",
                    str(root / "101.conf"),
                    "--out-dir",
                    str(root / "out"),
                ],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                marker.read_text(encoding="utf-8").splitlines(),
                [
                    "pve-conf-to-nix",
                    "--pve-conf",
                    str(root / "101.conf"),
                    "--out-dir",
                    str(root / "out"),
                ],
            )


if __name__ == "__main__":
    unittest.main()
