#!/usr/bin/env python3
"""Render the compatibility host authority wrapper.

The renderer consumes the current relay cache under /var/lib/proxnix and the
local Proxmox LXC configs under /etc/pve/lxc when available. It writes a
generated flake under /var/lib/proxnix/authority that exposes cluster-level
proxnix.containers plus a node view at proxnix.nodes.<node>.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import socket
import sys
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Any


VMID_RE = re.compile(r"^[0-9]+$")


def nix_str(value: Any) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${") + '"'


def nix_bool(value: bool) -> str:
    return "true" if value else "false"


def nix_attr_name(value: str) -> str:
    if re.match(r"^[A-Za-z_][A-Za-z0-9_'-]*$", value):
        return value
    return nix_str(value)


def atomic_write(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(mode)
    tmp.replace(path)


def copy_if_present(source: Path, dest: Path) -> bool:
    if not source.exists():
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)
    return True


def decode_ssh_public_keys(raw_value: str | None) -> list[str]:
    if not raw_value:
        return []
    decoded = urllib.parse.unquote(str(raw_value)).replace("\\n", "\n")
    return [
        line.strip()
        for line in decoded.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def parse_pve_conf(path: Path) -> dict[str, str]:
    raw: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("[") or ": " not in line:
            continue
        key, _, value = line.partition(": ")
        raw[key.strip()] = value.strip()
    return raw


def parse_bool(raw: str | None) -> bool | None:
    if raw is None:
        return None
    return raw in {"1", "true", "yes", "on"}


def normalize_pve(raw: dict[str, str]) -> dict[str, Any]:
    pve: dict[str, Any] = {}
    for key in ("ostype", "hostname", "rootfs", "net0", "features"):
        if raw.get(key):
            pve[key] = raw[key]
    for key in ("memory", "swap", "cores"):
        if raw.get(key):
            try:
                pve[key] = int(raw[key])
            except ValueError:
                pve[key] = raw[key]
    unprivileged = parse_bool(raw.get("unprivileged"))
    if unprivileged is not None:
        pve["unprivileged"] = unprivileged
    return pve


def proxmox_module(raw: dict[str, str]) -> str:
    lines = [
        "# Generated by proxnix-authority-render; do not edit by hand.",
        "{ lib, ... }: {",
    ]

    hostname = raw.get("hostname")
    if hostname:
        lines.append(f"  networking.hostName = lib.mkForce {nix_str(hostname)};")

    nameservers = raw.get("nameserver", "").split()
    if nameservers:
        rendered = " ".join(nix_str(item) for item in nameservers)
        lines.append(f"  networking.nameservers = lib.mkForce [ {rendered} ];")

    search_domain = raw.get("searchdomain")
    if search_domain:
        lines.append(f"  networking.search = lib.mkForce [ {nix_str(search_domain)} ];")

    ssh_keys = decode_ssh_public_keys(raw.get("ssh-public-keys"))
    if ssh_keys:
        rendered = " ".join(nix_str(item) for item in ssh_keys)
        lines.append(f"  users.users.root.openssh.authorizedKeys.keys = lib.mkForce [ {rendered} ];")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_modules_nix(has_site: bool, dropins: list[str]) -> str:
    lines = [
        "# Generated by proxnix-authority-render; do not edit by hand.",
        "[",
        "  ../../../modules/proxnix-guest-base.nix",
    ]
    if has_site:
        lines.append("  ../../legacy/site.nix")
    lines.append("  ./proxmox.nix")
    for dropin in dropins:
        lines.append(f"  ./dropins/{dropin}")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_pve_attrs(pve: dict[str, Any]) -> str:
    if not pve:
        return "{}"
    lines = ["{"]
    for key in sorted(pve):
        value = pve[key]
        if isinstance(value, bool):
            rendered = nix_bool(value)
        elif isinstance(value, int):
            rendered = str(value)
        else:
            rendered = nix_str(value)
        lines.append(f"      {nix_attr_name(key)} = {rendered};")
    lines.append("    }")
    return "\n".join(lines)


@dataclass(frozen=True)
class ContainerManifest:
    vmid: str
    hostname: str | None
    pve: dict[str, Any]
    placement: dict[str, Any]


def render_node_manifest(node_name: str, containers: list[ContainerManifest], source_revision: dict[str, Any] | None) -> str:
    local_vmids = [container.vmid for container in containers if container.placement.get("local")]
    lines = [
        "# Generated by proxnix-authority-render; do not edit by hand.",
        "{ self, lib }:",
        "let",
        "  systemPath = name: builtins.unsafeDiscardStringContext \"${self.nixosConfigurations.${name}.config.system.build.toplevel}\";",
        "in {",
        f"  nodeName = {nix_str(node_name)};",
        "  vmids = [",
    ]
    for container in containers:
        lines.append(f"    {nix_str(container.vmid)}")
    lines.extend([
        "  ];",
        "  localVmids = [",
    ])
    for vmid in local_vmids:
        lines.append(f"    {nix_str(vmid)}")
    lines.extend([
        "  ];",
        "  containers = {",
    ])
    source = "null" if source_revision is None else builtins_to_nix(source_revision, indent=4)
    for container in containers:
        system_attr = f"nixosConfigurations.ct{container.vmid}.config.system.build.toplevel"
        lines.extend([
            f"    {nix_attr_name(container.vmid)} = {{",
            f"      vmid = {container.vmid};",
            f"      hostname = {nix_str(container.hostname or f'ct{container.vmid}')};",
            f"      sourceRevision = {source};",
            f"      systemAttr = {nix_str(system_attr)};",
            f"      system = systemPath {nix_str('ct' + container.vmid)};",
            f"      pve = {render_pve_attrs(container.pve)};",
            f"      placement = {builtins_to_nix(container.placement, indent=6)};",
            "    };",
        ])
    lines.extend([
        "  };",
        "}",
        "",
    ])
    return "\n".join(lines)


def builtins_to_nix(value: Any, indent: int = 0) -> str:
    pad = " " * indent
    inner = " " * (indent + 2)
    if value is None:
        return "null"
    if isinstance(value, bool):
        return nix_bool(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return nix_str(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        rendered = " ".join(builtins_to_nix(item, indent=indent) for item in value)
        return f"[ {rendered} ]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = ["{"]
        for key in sorted(value):
            lines.append(f"{inner}{nix_attr_name(str(key))} = {builtins_to_nix(value[key], indent + 2)};")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    return nix_str(value)


def render_flake(node_name: str) -> str:
    return f"""# Generated by proxnix-authority-render; do not edit by hand.
{{
  description = "proxnix generated compatibility authority";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";

  outputs = {{ self, nixpkgs }}:
    let
      system = "x86_64-linux";
      lib = nixpkgs.lib;
      manifest = import ./generated/node-manifest.nix {{ inherit self lib; }};
      goldenTemplateModules =
        [ ./modules/proxnix-guest-base.nix ]
        ++ lib.optional (builtins.pathExists ./generated/legacy/site.nix) ./generated/legacy/site.nix;
      mkCt = vmid: lib.nixosSystem {{
        inherit system;
        modules = import ./generated/containers/${{vmid}}/modules.nix;
      }};
    in {{
      nixosConfigurations = {{
        proxnix-golden-template = lib.nixosSystem {{
          inherit system;
          modules = goldenTemplateModules;
        }};
      }} // builtins.listToAttrs (map (vmid: {{
        name = "ct${{vmid}}";
        value = mkCt vmid;
      }}) manifest.vmids);

      proxnix.containers = manifest.containers;
      proxnix.nodes.{nix_attr_name(node_name)} = manifest;
    }};
}}
"""


def load_source_revision(root: Path) -> dict[str, Any] | None:
    path = root / "publish-revision.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def render_authority(root: Path, authority: Path, pve_lxc_dir: Path, node_name: str) -> list[ContainerManifest]:
    generated = authority / "generated"
    legacy = generated / "legacy"
    modules = authority / "modules"
    containers_dir = root / "containers"

    authority.mkdir(parents=True, exist_ok=True)
    generated.mkdir(parents=True, exist_ok=True)
    modules.mkdir(parents=True, exist_ok=True)
    legacy.mkdir(parents=True, exist_ok=True)

    for filename in ("base.nix", "common.nix", "security-policy.nix"):
        source = root / filename
        if not source.exists():
            raise FileNotFoundError(f"required proxnix module missing: {source}")
        copy_if_present(source, modules / filename)

    has_site = copy_if_present(root / "site.nix", legacy / "site.nix")
    if not copy_if_present(root / "flake.lock", authority / "flake.lock"):
        (authority / "flake.lock").unlink(missing_ok=True)
    atomic_write(
        modules / "proxnix-guest-base.nix",
        "\n".join(
            [
                "# Generated by proxnix-authority-render; do not edit by hand.",
                "{ ... }: {",
                "  imports = [",
                "    ./base.nix",
                "    ./common.nix",
                "    ./security-policy.nix",
                "  ];",
                '  system.stateVersion = "25.11";',
                "}",
                "",
            ]
        ),
    )

    manifests: list[ContainerManifest] = []
    if containers_dir.exists():
        vmids = sorted(path.name for path in containers_dir.iterdir() if path.is_dir() and VMID_RE.match(path.name))
    else:
        vmids = []

    for vmid in vmids:
        pve_conf = pve_lxc_dir / f"{vmid}.conf"
        raw = parse_pve_conf(pve_conf) if pve_conf.exists() else {}
        container_out = generated / "containers" / vmid
        dropins_out = container_out / "dropins"
        dropins_out.mkdir(parents=True, exist_ok=True)

        dropin_names: list[str] = []
        dropin_dir = containers_dir / vmid / "dropins"
        if dropin_dir.exists():
            for source in sorted(dropin_dir.iterdir(), key=lambda item: item.name):
                if source.is_file() and source.suffix == ".nix":
                    copy_if_present(source, dropins_out / source.name)
                    dropin_names.append(source.name)

        atomic_write(container_out / "proxmox.nix", proxmox_module(raw))
        atomic_write(container_out / "modules.nix", render_modules_nix(has_site, dropin_names))
        placement = {
            "local": False,
            "node": None,
            "observedPveConfig": pve_conf.exists(),
        }
        manifests.append(ContainerManifest(vmid=vmid, hostname=raw.get("hostname"), pve=normalize_pve(raw), placement=placement))

    atomic_write(authority / "flake.nix", render_flake(node_name))
    atomic_write(generated / "node-manifest.nix", render_node_manifest(node_name, manifests, load_source_revision(root)))
    return manifests


def default_node_name() -> str:
    return socket.gethostname().split(".", 1)[0] or "localhost"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render proxnix compatibility authority wrapper")
    parser.add_argument("--root", default="/var/lib/proxnix", help="proxnix relay root")
    parser.add_argument("--authority", default=None, help="authority output directory")
    parser.add_argument("--pve-lxc-dir", default="/etc/pve/lxc", help="Proxmox LXC config directory")
    parser.add_argument("--node-name", default=default_node_name(), help="node manifest name")
    parser.add_argument("--print-manifest", action="store_true", help="print generated node-manifest.nix")
    args = parser.parse_args(argv)

    root = Path(args.root)
    authority = Path(args.authority) if args.authority else root / "authority"
    try:
        manifests = render_authority(root, authority, Path(args.pve_lxc_dir), args.node_name)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.print_manifest:
        print((authority / "generated" / "node-manifest.nix").read_text(encoding="utf-8"), end="")
    else:
        print(f"rendered {len(manifests)} container(s) for node {args.node_name} into {authority}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
